Repository openrails/openrails, pull requests merged in 2019-05, with the labels that each got.

#33 Upgrade all projects to target NetFX 4.7.2
  Source/3rdPartyLibs/GNU.Getopt.dll
  Source/3rdPartyLibs/GNU.Gettext.Msgfmt.exe
  Source/3rdPartyLibs/GNU.Gettext.WinForms.dll
  Source/3rdPartyLibs/GNU.Gettext.Xgettext.exe
  Source/3rdPartyLibs/GNU.Gettext.dll
  Source/ContentChecker/ContentChecker.csproj
  Source/ContentChecker/app.config
  Source/Contrib/ActivityEditor/AEWizard/AEWizard.csproj
  Source/Contrib/ActivityEditor/AEWizard/Properties/Resources.Designer.cs
  Source/Contrib/ActivityEditor/AEWizard/Properties/Settings.Designer.cs
  Source/Contrib/ActivityEditor/ActivityEditor/ActivityEditor.csproj
  Source/Contrib/ActivityEditor/ActivityEditor/Internat/IntalMngr.cs
  Source/Contrib/ActivityEditor/ActivityEditor/Properties/Resources.Designer.cs
  Source/Contrib/ActivityEditor/ActivityEditor/Properties/Settings.Designer.cs
  Source/Contrib/ActivityEditor/ActivityEditor/app.config
  Source/Contrib/ActivityEditor/LibAE/LibAE.csproj
  Source/Contrib/ContentManager/ContentManager.csproj
  Source/Contrib/ContentManager/Properties/Resources.Designer.cs
  Source/Contrib/ContentManager/Properties/Settings.Designer.cs
  Source/Contrib/ContentManager/app.config
  Source/Contrib/DataCollector/DataCollector.csproj
  Source/Contrib/DataCollector/app.config
  Source/Contrib/DataConverter/DataConverter.csproj
  Source/Contrib/DataConverter/app.config
  Source/Contrib/DataValidator/DataValidator.csproj
  Source/Contrib/DataValidator/app.config
  Source/Contrib/TrackViewer/Properties/Resources.Designer.cs
  Source/Contrib/TrackViewer/Properties/Settings.Designer.cs
  Source/Contrib/TrackViewer/TrackViewer.csproj
  Source/Contrib/TrackViewer/app.config
  Source/Launcher/Launcher.csproj
  Source/Menu/MainForm.cs
  Source/Menu/Menu.csproj
  Source/Menu/Properties/Resources.Designer.cs
  Source/Menu/app.config
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Content/ORTS.Content.csproj
  Source/ORTS.IO/ORTS.IO.csproj
  Source/ORTS.Menu/ORTS.Menu.csproj
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Updater/ORTS.Updater.csproj
  Source/Orts.Formats.Msts/Orts.Formats.Msts.csproj
  Source/Orts.Formats.OR/Orts.Formats.OR.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.OR/Orts.Parsers.OR.csproj
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/RunActivity/Program.cs
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Processes/Game.cs
  Source/RunActivity/Viewer3D/Processes/LoaderProcess.cs
  Source/RunActivity/app.config
  Source/Tests/Tests.csproj
  Source/Updater/Updater.csproj
  Source/Updater/UpdaterProgress.cs
  Source/Updater/app.config
Labels: enhancement

#56 CopyCreate LAA-exe .config file
  Build.cmd
Labels: bug

#58 Bug fix for "Scripts don't work any more"
  Source/Orts.Simulation/Common/Scripting/ScriptManager.cs
Labels: bug

#60 Manually re-route AI trains through dispatcher window
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: enhancement

#61 Update OR manual with info about manually re-routing AI trains
  Source/Documentation/Manual/driving.rst
Labels: documentation

#59 Update POT files and French locales. Fix for https://bugs.launchpad.net/or/+bug/1830120
  Source/Locales/Contrib/qps-ploc.po
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/fr.po
  Source/Locales/Menu/qps-ploc.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/cs.po
  Source/Locales/ORTS.Common/da.po
  Source/Locales/ORTS.Common/de.po
  Source/Locales/ORTS.Common/fr.po
  Source/Locales/ORTS.Common/hu.po
  Source/Locales/ORTS.Common/it.po
  Source/Locales/ORTS.Common/qps-ploc.po
  Source/Locales/ORTS.Common/zh-CN.po
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Menu/fr.po
  Source/Locales/ORTS.Menu/qps-ploc.po
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/ORTS.Settings/cs.po
  Source/Locales/ORTS.Settings/da.po
  Source/Locales/ORTS.Settings/de.po
  Source/Locales/ORTS.Settings/fr.po
  Source/Locales/ORTS.Settings/hu.po
  Source/Locales/ORTS.Settings/it.po
  Source/Locales/ORTS.Settings/qps-ploc.po
  Source/Locales/ORTS.Settings/zh-CN.po
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/qps-ploc.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/qps-ploc.po
  Source/ORTS.Settings/InputSettings.cs
Labels: bug, enhancement

#63 When .s file requires missing .dds file, the equivalent .ace is picked if existing
  Source/RunActivity/Viewer3D/Materials.cs
Labels: bug
