Repository openrails/openrails, pull requests merged in 2019-09, with the labels that each got.

#96 Contact page re-directed
  Website/openrails.org/contact/index.php
Labels: website

#100 Add warning if train has no locomotive but is required
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: enhancement

#74 Removing on screen notifications of camera change
  Source/RunActivity/Viewer3D/Popups/NoticeWindow.cs
Labels: enhancement

#75 Change of default cabview font type and dimension
  Source/Orts.Formats.Msts/CabViewFile.cs
Labels: enhancement

#94 Water trough
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/GearBox.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#98 https://blueprints.launchpad.net/or/+spec/refactor-dynamic-brakeforce…
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: refactoring

#97 https://blueprints.launchpad.net/or/+spec/wheel-bearing-impacts - mov…
  Source/Orts.Formats.Msts/ActivityFile.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement
