Repository openrails/openrails, pull requests merged in 2019-10, with the labels that each got.

#76 Enable disable control confirmations in game
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#106 Update OR manual: online toggle of control confirmations
  Source/Documentation/Manual/options.rst
Labels: documentation

#107 Improvements to diesel performance
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
Labels: enhancement

#108 Adjust cab stretch for square cab textures wider than 1024 x 1024 pixels
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug

#110 Fix bug of stop signal skipped when inside platform
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
Labels: bug

#113 Bug fix for https://bugs.launchpad.net/or/+bug/1848878 AI train WP restart events don't work after save
  Source/Orts.Simulation/Simulation/AIs/AIAuxAction.cs
Labels: bug
