Repository openrails/openrails, pull requests merged in 2019-04, with the labels that each got.

#34 Upgrade all projects to C# 7.3
  Source/ContentChecker/ContentChecker.csproj
  Source/Contrib/ActivityEditor/AEWizard/AEWizard.csproj
  Source/Contrib/ActivityEditor/ActivityEditor/ActivityEditor.csproj
  Source/Contrib/ActivityEditor/LibAE/LibAE.csproj
  Source/Contrib/ContentManager/ContentManager.csproj
  Source/Contrib/DataCollector/DataCollector.csproj
  Source/Contrib/DataConverter/DataConverter.csproj
  Source/Contrib/DataValidator/DataValidator.csproj
  Source/Contrib/TrackViewer/TrackViewer.csproj
  Source/Launcher/Launcher.csproj
  Source/Menu/Menu.csproj
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Content/ORTS.Content.csproj
  Source/ORTS.IO/ORTS.IO.csproj
  Source/ORTS.Menu/ORTS.Menu.csproj
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Updater/ORTS.Updater.csproj
  Source/ORTS.Viewer3D/ORTS.Viewer3D.csproj
  Source/Orts.Formats.Msts/Orts.Formats.Msts.csproj
  Source/Orts.Formats.OR/Orts.Formats.OR.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.OR/Orts.Parsers.OR.csproj
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/RunActivity/RunActivity.csproj
  Source/Tests/Tests.csproj
  Source/Updater/Updater.csproj
Labels: enhancement

#39 Checking for new dependencies required for upgrade and MG
  Source/3rdPartyLibs/OpenAL32.dll
  Source/Launcher/Launcher.csproj
  Source/Launcher/Program.cs
  Source/RunActivity/RunActivity.csproj
Labels: enhancement

#44 Bug fix for "Lights incorrectly are on in uncoupled loco"
  Source/RunActivity/Viewer3D/Lights.cs
Labels: bug

#41 Correct vacuum brake issues
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#23 https://blueprints.launchpad.net/or/+spec/water-trough-filling - base…
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
  Source/RunActivity/Viewer3D/Wire.cs
Labels: enhancement

#47 Cleanup unused projects
  Source/ORTS.Parsers/ORTS.Parsers.csproj
  Source/ORTS.Parsers/Properties/AssemblyInfo.cs
  Source/ORTS.Viewer3D/ORTS.Viewer3D.csproj
  Source/ORTS.Viewer3D/Properties/AssemblyInfo.cs
  Source/ORTS.sln
Labels: enhancement

#21 Timetable Update, including starting in paused state.
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
  Source/Orts.Simulation/Simulation/Timetables/TTPool.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Popups/NextStationWindow.cs
  Source/RunActivity/Viewer3D/Popups/TTDetachWindow.cs
  Source/RunActivity/Viewer3D/Processes/GameStateViewer3D.cs
Labels: bug, enhancement

#52 Removing check and empty file creation
  Source/RunActivity/Viewer3D/OpenAL.cs
Labels: bug

#54 Avoid precipitation inside 3D cab.
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#53 Fix crash when activity event triggered at game start.
  Source/RunActivity/Viewer3D/Popups/ActivityWindow.cs
Labels: bug
