Repository openrails/openrails, pull requests merged in 2020-01, with the labels that each got.

#131 Bug fix for https://bugs.launchpad.net/or/+bug/1858032 Errors in station stops after manual mode
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/RunActivity/Viewer3D/Popups/NextStationWindow.cs
Labels: bug

#132 Bug fix for https://bugs.launchpad.net/or/+bug/1858135 Station stop sequence damaged after switching to autopilot
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
Labels: bug

#130 Bug fix for https://bugs.launchpad.net/or/+bug/1857203 Sound thread safety crash
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Pantograph.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/RunActivity/Viewer3D/Sound.cs
Labels: bug

#128 Bug fix for https://bugs.launchpad.net/or/+bug/1857754 Uncomfortable manual gear up/down
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
Labels: bug

#121 Mouse wheel scrolling in-game and Dragging scrollbars in-game
  Source/RunActivity/Viewer3D/Popups/Window.cs
  Source/RunActivity/Viewer3D/Popups/WindowControls.cs
  Source/RunActivity/Viewer3D/Popups/WindowManager.cs
  Source/RunActivity/Viewer3D/UserInput.cs
Labels: enhancement

#136 Bug fix for https://bugs.launchpad.net/or/+bug/1860263 System.ArgumentException at System.Array.Copy
  Source/RunActivity/Viewer3D/RollingStock/TrainCarViewer.cs
Labels: bug

#122 Water Scoop Bug fix
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#133 Bug fix for https://bugs.launchpad.net/or/+bug/1858218 Gearbox not managed correctly for AI and autopiloted trains
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSElectricLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#137 Harmonize initialization of autopilotable player train with that of standard player trains
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: bug

#139 Bug fix for https://bugs.launchpad.net/or/+bug/1858655 Helpers not throttled to zero when de-MUed
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#135 Website/svn to git
  Website/openrails.org/contribute/developing-code/index.php
  Website/openrails.org/download/source/index.php
Labels: website

#140 Bug fix for https://bugs.launchpad.net/or/+bug/1861261 Turntable camera views rotate by 180 degrees
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: bug
