Repository openrails/openrails, pull requests merged in 2020-08, with the labels that each got.

#249 Trackmonitor and train driving webpages in a single one.
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitorTrainDriving/SignalAspects.png
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitorTrainDriving/TrackMonitorImages.png
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitorTrainDriving/index.css
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitorTrainDriving/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitorTrainDriving/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/index.html
Labels: enhancement

#250 Bug fix for https://bugs.launchpad.net/or/+bug/1890585 Crash when switching from a 2D cab loco to a 3D cab only loco
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug

#252 Script compilation with Roslyn in order to support C# v7
  Source/Orts.Simulation/Common/Scripting/ScriptManager.cs
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/packages.config
Labels: enhancement

#234 Rehabilitate unit testing suite, migrate to xUnit 2
  Source/3rdPartyLibs/xunit.dll
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/Tests/AssertWarnings.cs
  Source/Tests/Orts.Common/Conversions.cs
  Source/Tests/Orts.Parsers.Msts/StfReader.cs
  Source/Tests/Orts.Parsers.OR/TimetableReaderTests.cs
  Source/Tests/Tests.csproj
  Source/Tests/packages.config
  Source/Tests/xunit.runner.json
  Website/openrails.org/contribute/developing-code/index.php
Labels: refactoring

#243 Fix lack of friction for wagons using freight animations with Davis values: https://bugs.launchpad.net/or/+bug/1889448
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug

#248 Russian translation
  Source/Locales/Contrib/Contrib.pot
  Source/Locales/Contrib/ru.po
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/ru.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/ru.po
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/Orts.Formats.OR/Orts.Formats.OR.pot
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/ru.po
  Source/Locales/Updater/Updater.pot
Labels: for-unstable, locales

#253 Fix translations not displaying for the HUD Dispatcher Information tab: https://bugs.launchpad.net/or/+bug/1891066
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: bug

#228 adds links to OR on Elvas Tower
  Website/openrails.org/contact/form.php
  Website/openrails.org/contact/index.php
  Website/openrails.org/contribute/developing-code/index.php
  Website/openrails.org/discover/project-team/index.php
  Website/openrails.org/share/community/index.php
Labels: website

#254 New signalling functions: Advanced callon, by roeter
  Source/Documentation/Manual/operation.rst
  Source/Documentation/Manual/start.rst
  Source/Orts.Formats.Msts/SignalScripts.cs
  Source/Orts.Simulation/Simulation/Signalling/SIGSCRfile.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: enhancement

#241 Fixed delayed opening of signals on high speed lines in explorer mode https://bugs.launchpad.net/or/+bug/1613304
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: bug, refactoring

#244 expanded Variable Sound Triggers
  Source/Documentation/Manual/sound.rst
Labels: documentation

#245 Manual build fixes
  Source/Documentation/Manual/physics.rst
  Source/Documentation/Manual/start.rst
Labels: documentation

#251 Change 3D cab key behaviour + French locale updates
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/driving.rst
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/fr.po
  Source/Locales/Menu/qps-ploc.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/fr.po
  Source/Locales/ORTS.Common/qps-ploc.po
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Menu/fr.po
  Source/Locales/ORTS.Menu/qps-ploc.po
  Source/Locales/ORTS.Settings/qps-ploc.po
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/fr.po
  Source/Locales/Orts.Simulation/qps-ploc.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/fr.po
  Source/Locales/RunActivity/qps-ploc.po
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/Commands.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement, locales

#255 Refactor MultiTTFilePreliminaryRead and MultiTTFileRead into a common function: https://blueprints.launchpad.net/or/+spec/separate-multitt
  Source/Orts.Formats.OR/TimetableGroupFile.cs
Labels: refactoring

#257 Missing link restored
  Source/Documentation/Manual/driving.rst
Labels: documentation

#256 Manual signal functions
  Source/Documentation/Manual/appendices.rst
Labels: documentation

#259 Fix duplicate couplers upon resuming from save: https://bugs.launchpad.net/or/+bug/1892403
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug

#266 Pop to front
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.Designer.cs
Labels: enhancement, question
