Repository openrails/openrails, pull requests merged in 2020-10, with the labels that each got.

#289 Re-insert pt-PT menu locale, by Aldarion-CP Virtual
  Source/Locales/Menu/pt-PT.po
Labels: locales

#283 Implement static features-only mode for the Track Monitor: https://blueprints.launchpad.net/or/+spec/static-track-monitor
  Source/Documentation/Manual/driving.rst
  Source/ORTS.Settings/InputSettings.cs
  Source/RunActivity/Content/SVG Source Images/SignalAspects.svg
  Source/RunActivity/Content/SignalAspects.png
  Source/RunActivity/Viewer3D/Popups/TrackMonitorWindow.cs
Labels: enhancement

#294 Adjust hotbox code
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug

#291 Expand to max 48 TCS commands
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement

#295 Add notes to manual on hotbox function
  Source/Documentation/Manual/physics.rst
Labels: documentation

#290 Fix calculation issues with TE and Speed
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: enhancement

#296 Fix manual build warnings
  Source/Documentation/Manual/physics.rst
Labels: documentation

#288 Add water mass to diesel locomotive mass
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSElectricLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug
