Repository openrails/openrails, pull requests merged in 2020-09, with the labels that each got.

#263 Timetable briefing ingame
  Source/Documentation/Manual/timetable.rst
  Source/Menu/MainForm.cs
  Source/Orts.Formats.OR/TimetableFile.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
  Source/RunActivity/Viewer3D/Popups/HelpWindow.cs
Labels: enhancement

#272 build: Add index to PDFs
  Source/Documentation/Manual/index.rst
  Source/Documentation/Manual/make.bat
Labels: documentation

#274 Bug fix for https://bugs.launchpad.net/or/+bug/1893565 Pantograph control sequence does not work correctly
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: bug

#260 compile warnings resolved
  Source/Contrib/ActivityEditor/ActivityEditor/Engine/ActEditor.cs
  Source/Contrib/ActivityEditor/ActivityEditor/Engine/Viewer2D.cs
  Source/ORTS.Common/SystemInfo.cs
  Source/Orts.Formats.Msts/ActivityFile.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/RunActivity/Viewer3D/Popups/HelpWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: refactoring

#270 Revert and new fix for https://bugs.launchpad.net/or/+bug/1613304
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: bug

#273 Update timetable documentation
  Source/Documentation/Manual/timetable.rst
Labels: documentation

#269 Move the tracking camera pivot to the center of the railcar
  Source/RunActivity/Viewer3D/Cameras.cs
Labels: enhancement

#271 Manual Braking
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement

#277 feat: Clean up Sphinx build and configuration
  .gitignore
  Build.cmd
  Source/Documentation/Manual/Makefile
  Source/Documentation/Manual/conf.py
  Source/Documentation/Manual/make.bat
Labels: refactoring

#279 Add missing turntable paths image
  Source/Documentation/Manual/images/turntable-paths.jpg
Labels: documentation

#278 Bug fix for https://bugs.launchpad.net/or/+bug/1895692 False done indication on drop cars at location; by edwardk
  Source/Orts.Simulation/Simulation/Activity.cs
Labels: bug

#275 Adds index of parameters to Manual
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/features-route.rst
  Source/Documentation/Manual/index.rst
  Source/Documentation/Manual/operation.rst
  Source/Documentation/Manual/options.rst
  Source/Documentation/Manual/physics.rst
  Source/Documentation/Manual/software-platform.rst
  Source/Documentation/Manual/sound.rst
Labels: documentation
