Repository openrails/openrails, pull requests merged in 2020-07, with the labels that each got.

#224 Additional Sound Events
  Source/Documentation/Manual/sound.rst
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: enhancement, for-unstable

#229 Fix MSTS-compatible physics reverting to Davis physics: https://bugs.launchpad.net/or/+bug/1886566
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug

#221 Refactor try-catch blocks in RunActivity
  Source/RunActivity/Processes/Profiler.cs
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
  Source/RunActivity/Viewer3D/Debugging/MessageViewer.Designer.cs
  Source/RunActivity/Viewer3D/Debugging/MessageViewer.cs
  Source/RunActivity/Viewer3D/MSTSSky.cs
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/Popups/ComposeMessage.cs
  Source/RunActivity/Viewer3D/Processes/Game.cs
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
  Source/RunActivity/Viewer3D/Weather.cs
Labels: for-unstable, refactoring

#225 Fix advanced adhesion wheelslip upon resuming from save: https://bugs.launchpad.net/or/+bug/1294410
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
Labels: bug

#145 Advanced Coupler Functionality
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement

#233 Remove startup exception in the launcher by refactoring a try-catch
  Source/ORTS.Menu/Consists.cs
Labels: refactoring

#216 Upgrade and replace web server with EmbedIO
  Build.cmd
  Source/Documentation/Manual/options.rst
  Source/RunActivity/Content/Web/HUD.html
  Source/RunActivity/Content/Web/css/sample.css
  Source/RunActivity/Content/Web/css/trackmonitor.css
  Source/RunActivity/Content/Web/images/waverley.jpg
  Source/RunActivity/Content/Web/images/zig-zag.jpg
  Source/RunActivity/Content/Web/index - ApiSample.html
  Source/RunActivity/Content/Web/index.html
  Source/RunActivity/Content/Web/js/ApiSample.js
  Source/RunActivity/Content/Web/js/ApiTrainInfo.js
  Source/RunActivity/Content/Web/js/hud.js
  Source/RunActivity/Content/Web/js/trackmonitor.js
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Processes/WebServerProcess.cs
  Source/RunActivity/Viewer3D/WebServices/Web/APISample/index.css
  Source/RunActivity/Viewer3D/WebServices/Web/APISample/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/APISample/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/APISample/or_logo.png
  Source/RunActivity/Viewer3D/WebServices/Web/HUD.html
  Source/RunActivity/Viewer3D/WebServices/Web/HUD/index.css
  Source/RunActivity/Viewer3D/WebServices/Web/HUD/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/HUD/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitor/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitor/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/css/hud.css
  Source/RunActivity/Viewer3D/WebServices/Web/css/sample.css
  Source/RunActivity/Viewer3D/WebServices/Web/css/trackmonitor.css
  Source/RunActivity/Viewer3D/WebServices/Web/images/waverley.jpg
  Source/RunActivity/Viewer3D/WebServices/Web/images/zig-zag.jpg
  Source/RunActivity/Viewer3D/WebServices/Web/index - ApiSample.html
  Source/RunActivity/Viewer3D/WebServices/Web/index.css
  Source/RunActivity/Viewer3D/WebServices/Web/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/js/ApiSample.js
  Source/RunActivity/Viewer3D/WebServices/Web/js/ApiTrainInfo.js
  Source/RunActivity/Viewer3D/WebServices/Web/js/hud.js
  Source/RunActivity/Viewer3D/WebServices/Web/js/trackmonitor.js
  Source/RunActivity/Viewer3D/WebServices/Web/or_logo.png
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
  Source/RunActivity/packages.config
Labels: for-unstable

#238 Allow the webserver to listen on all IP addresses: https://blueprints.launchpad.net/or/+spec/embedio-for-web-server
  Source/RunActivity/Viewer3D/Processes/WebServerProcess.cs
Labels: bug

#237 Fixed 3D cab loading with undefined cabview control in CVF file https://bugs.launchpad.net/or/+bug/1888945
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#226 EmbedIO web server graphical track monitor
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/WebServices/TrackMonitorDisplay.cs
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitor/SignalAspects.png
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitor/TrackMonitorImages.png
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitor/index.css
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitor/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitor/index.js
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
Labels: enhancement, for-unstable

#242 docs: Rewrite readme to point people towards many more useful places
  README.md
Labels: documentation
