Repository openrails/openrails, pull requests merged in 2020-04, with the labels that each got.

#159 Bug fix for https://bugs.launchpad.net/or/+bug/1873915 Forced approach position control clears far from the signal
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: bug

#156 Update of and improvements to German locales of ORTS.Common
  Source/Locales/Contrib/Contrib.pot
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/de.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/de.po
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Menu/de.po
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/Orts.Formats.OR/Orts.Formats.OR.pot
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/de.po
  Source/Locales/Updater/Updater.pot
Labels: enhancement

#158 Bug fix for https://bugs.launchpad.net/or/+bug/1873631 Level Crossing does not close when a multiplayer train passes
  Source/Orts.Simulation/Simulation/LevelCrossing.cs
Labels: bug

#150 Other way to fix bug https://bugs.launchpad.net/or/+bug/1858135 Station stop sequence damaged after switching to autopilot
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Activity.cs
Labels: bug

#166 Bug fix for https://bugs.launchpad.net/or/+bug/1874240 route_cleared_to_signal not working for non NORMAL signals
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: bug

#167 Add menu translation for pt-PT, by Aldarion
  Source/Locales/ORTS.Menu/pt_PT.po
Labels: enhancement

#141 Brazilian Portuguese localization, by Diter Otaviano & William Araújo
  Source/Locales/Contrib/pt-BR.po
  Source/Locales/Menu/pt-BR.po
  Source/Locales/ORTS.Common/pt-BR.po
  Source/Locales/ORTS.Menu/pt-BR.po
  Source/Locales/ORTS.Settings/pt-BR.po
  Source/Locales/Orts.Formats.OR/pt-BR.po
  Source/Locales/Orts.Simulation/pt-BR.po
  Source/Locales/RunActivity/pt-BR.po
  Source/Locales/Updater/pt-BR.po
Labels: enhancement

#138 Bug fix for https://bugs.launchpad.net/or/+bug/1858298 Sound problems when viewer not created in initial conditions
  Source/RunActivity/Viewer3D/RollingStock/MSTSDieselLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSElectricLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Sound.cs
Labels: bug

#146 Bug fix for https://bugs.launchpad.net/or/+bug/1868278 AI train authorization to pass red signal not saved
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: bug

#149 Bug fix for https://bugs.launchpad.net/or/+bug/1870990 ArgumentOutOfRangeException at TrainCar.IsOverTrough()
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: bug

#160 Signed traction-braking control
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: enhancement

#161 Bug fix for https://bugs.launchpad.net/or/+bug/1463537 Flashing MSTSwater
  Source/RunActivity/Viewer3D/RenderFrame.cs
Labels: bug

#165 Bug fix for https://bugs.launchpad.net/or/+bug/1874209 Waiting point does not expire
  Source/Orts.Simulation/Simulation/AIs/AIAuxAction.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Activity.cs
  Source/Orts.Simulation/Simulation/LevelCrossing.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
Labels: bug

#142 Update Diesel Performance
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: enhancement

#171 Document C# scripting in the manual
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/images/features-scripting1.png
  Source/Documentation/Manual/images/features-scripting2.png
  Source/Documentation/Manual/images/features-scripting3.png
  Source/Documentation/Manual/images/features-scripting4.png
  Source/Documentation/Manual/physics.rst
Labels: documentation

#173 GetValidWindowSize
  Source/Menu/Options.cs
Labels: bug

#174 update-polish-link
  Website/openrails.org/share/community/index.php
Labels: website
