Repository openrails/openrails, pull requests merged in 2020-12, with the labels that each got.

#312 Some locomotive related TCS script hooks, see https://blueprints.launchpad.net/or/+spec/locomotive-related-tcs-hooks
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Pantograph.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
Labels: enhancement

#314 Play a standardized, pleasing sound when taking a screenshot
  Source/Orts.Simulation/Common/Events.cs
  Source/RunActivity/Content/TakeScreenshot.wav
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Sound.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#319 notrriggered => nottriggered x 2
  Source/Orts.Formats.Msts/ActivityFile.cs
Labels: bug

#300 Brake pipe overcharge
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
Labels: enhancement, for-unstable

#316 add webpage learn > physics
  Website/openrails.org/learn/physics/index.php
  Website/openrails.org/shared/menu.php
Labels: website

#293 Further TCS handles to get signal data and to set sound events
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#317 Bug fix for https://bugs.launchpad.net/or/+bug/1906786 - Approach Control doesn't work for non NORMAL signals
  Source/Documentation/Manual/operation.rst
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: enhancement, for-unstable

#318 Reintroduce "Allowing manual Call On from dispatcher window" - https://trello.com/c/I19VVKlz/450-manual-call-on-from-dispatcher-window
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/operation.rst
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/SIGSCRfile.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
Labels: enhancement, for-unstable

#327 Refine CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation

#326 Update to News section on website home page
  Website/openrails.org/index.php
Labels: website

#324 Mark signal glow material for not loosing it.
  Source/RunActivity/Viewer3D/Signals.cs
Labels: bug, for-unstable

#329 Display shadow only behind text in on-screen messages
  Source/RunActivity/Viewer3D/Popups/MessagesWindow.cs
Labels: enhancement
