Repository openrails/openrails, pull requests merged in 2020-05, with the labels that each got.

#102 https://blueprints.launchpad.net/or/+spec/stock-visual-effects - chan…
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement

#157 Review of Steam Locomotive Manual Firing Functionality
  Source/Documentation/Manual/physics.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#181 Bug fix for https://bugs.launchpad.net/or/+bug/1877037 Station stop sequence damaged in autopilot mode
  Source/Orts.Simulation/Simulation/Activity.cs
Labels: bug

#170 TCS extensions: Starting version for Unstable release
  Source/Documentation/Manual/features-rollingstock.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Common/Scripting/Commands.cs
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/CircuitBreaker.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#189 Bug fix for https://bugs.launchpad.net/or/+bug/1878687 Maximum gauge allowed smaller than Iberian gauge
  Source/Menu/Options.Designer.cs
Labels: bug

#182 https://trello.com/c/uwEpTruy/459-make-autopilot-and-extended-ai-shunting-always-on
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/images/options-experimental.png
  Source/Documentation/Manual/images/options-simulation.png
  Source/Documentation/Manual/operation.rst
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/Menu/Options.resx
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
Labels: enhancement

#187 Bug fix for https://bugs.launchpad.net/or/+bug/1877644 - SPEED signals not being updated in multiplayer clients
  Source/Orts.Simulation/MultiPlayer/Message.cs
Labels: for-unstable

#103 Changes to vacuum brakes
  Source/Documentation/Manual/physics.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/BrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSDieselLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#143 Update of French locales, by septf
  Source/Locales/Contrib/fr.po
  Source/Locales/Orts.Simulation/fr.po
  Source/Locales/RunActivity/fr.po
Labels: enhancement

#195 Fix the order sequence for Consist and Path.
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: for-unstable

#198 https://trello.com/c/8RK0kuCt/465-enable-rotation-for-digital-2d-cabview-controls
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/images/cabs-digitals-rotation.png
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/RunActivity/Viewer3D/Popups/WindowText.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement
