Repository openrails/openrails, pull requests merged in 2020-06, with the labels that each got.

#200 Bug fix for https://bugs.launchpad.net/or/+bug/1573599. Error when exiting the game.
  Source/RunActivity/Viewer3D/Processes/UpdaterProcess.cs
Labels: for-unstable

#219 fix: Remove VS2015 from supported build environments
  Website/openrails.org/contribute/developing-code/index.php
Labels: website

#205 Traction-braking cabview control considering also train brake
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: enhancement

#208 Bug fix for https://bugs.launchpad.net/or/+bug/1882499 OR requires first number > 1 in animation ( 1 1
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: bug

#183 restored BNSF Scenic Route and updated link to Broad Gauge Productions
  Website/openrails.org/index.php
  Website/openrails.org/trade/index.php
Labels: website

#209 Enable rotation of digital clock cab control; by Paolo
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
Labels: enhancement

#214 Fix annoying startup exception when running with a debugger attached
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
Labels: for-unstable

#203 Extended starting friction parameters
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: not-for-unstable

#222 Record current speed limit in the data logger
  Source/RunActivity/Viewer3D/InfoDisplay.cs
Labels: enhancement

#223 Fix for https://bugs.launchpad.net/or/+bug/1885572 . TrackMonitor left/right switch position not scaled.
  Source/RunActivity/Viewer3D/Popups/TrackMonitorWindow.cs
Labels: bug

#220 Further TCS extensions
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Orts.Simulation/Common/Scripting/Commands.cs
  Source/Orts.Simulation/Common/Scripting/Common.cs
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement, for-unstable
