Repository openrails/openrails, pull requests merged in 2021-02, with the labels that each got.

#345 Bug fix for https://bugs.launchpad.net/or/+bug/1912683. Tapping on the OR-icon, it didn’t change anything.
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitorTrainDriving/index.js
Labels: bug

#346 Fix mispositioned digital cab displays in letterboxing mode
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#336 Add secret button to access launcher arguments for easier debugging
  Source/Menu/Program.cs
Labels: enhancement

#348 Adjust water scoop sounds
  Source/Documentation/Manual/sound.rst
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: enhancement

#349 adds section on parameters with links to spreadsheet
  .gitignore
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/developing.rst
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/features-route.rst
  Source/Documentation/Manual/operation.rst
  Source/Documentation/Manual/options.rst
  Source/Documentation/Manual/physics.rst
Labels: documentation

#352 Enforce EQ pressure minimal reduction at service rate
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
Labels: bug

#292 SignalScript parsing reports unnecessary exceptions
  Source/Orts.Formats.Msts/SignalScripts.cs
Labels: refactoring

#351 Trim whitespace from timetable-or cells
  Source/Orts.Parsers.OR/TimetableReader.cs
Labels: enhancement

#354 add Learn > Activities page
  Website/openrails.org/learn/activities/GuideExample.jpg
  Website/openrails.org/learn/activities/index.php
  Website/openrails.org/shared/menu.php
Labels: website

#355 added missing entry for Options - Simulation
  Source/Documentation/Manual/images/options-simulation.png
  Source/Documentation/Manual/options.rst
Labels: documentation

#339 Initial functionality for Eames (straight) vacuum brake.
  Source/Documentation/Manual/physics.rst
  Source/Documentation/Manual/sound.rst
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/MSTSBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/StraightVacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: enhancement

#353 Sound section corrected
  Source/Documentation/Manual/sound.rst
Labels: documentation

#356 Fix stuttering effect in 3D cabs: https://bugs.launchpad.net/or/+bug/1878975
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: bug

#358 Fix cab letterboxing memory leak: https://bugs.launchpad.net/or/+bug/1885342
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#359 Refactor signal script term parser
  Source/Orts.Formats.Msts/SignalScripts.cs
Labels: refactoring

#347 https://blueprints.launchpad.net/or/+spec/horn-blow-sequence American horn blow sequence for AI trains
  Source/Contrib/TrackViewer/Editing/WaitPointDialog.xaml
  Source/Contrib/TrackViewer/Editing/WaitPointDialog.xaml.cs
  Source/Documentation/Manual/operation.rst
  Source/ORTS.Common/enums.cs
  Source/Orts.Formats.Msts/ActivityFile.cs
  Source/Orts.Formats.OR/AuxActionRef.cs
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/AIs/AIAuxAction.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/LevelCrossing.cs
Labels: enhancement
