Repository openrails/openrails, pull requests merged in 2021-03, with the labels that each got.

#360 Bug fix for https://bugs.launchpad.net/or/+bug/1916525. TimeTable mode, #settings for storage area, fails.
  Source/Orts.Simulation/Simulation/Timetables/TTPool.cs
Labels: bug

#362 Correct null value bug
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
Labels: bug

#370 Bug fix for https://bugs.launchpad.net/or/+bug/1917796 Crash on waiting point for AI horn blow
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
Labels: bug

#366 added 2 more items to Learn > Activities
  Website/openrails.org/learn/activities/index.php
Labels: website

#372 removed unwanted section number
  Source/Documentation/Manual/timetable.rst
Labels: documentation

#364 Added new items since v1.3
  Source/Documentation/Manual/news.rst
Labels: documentation

#297 Timetable trains shown on a map v2
  Source/Documentation/Manual/appendices.rst
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/images/options-general.png
  Source/Documentation/Manual/images/timetable_tab1.png
  Source/Documentation/Manual/images/timetable_tab2.png
  Source/Documentation/Manual/images/timetable_tab3.png
  Source/Documentation/Manual/images/timetable_tab4.png
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.Designer.cs
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.resx
  Source/RunActivity/Viewer3D/Debugging/TimetableWindow.cs
  Source/RunActivity/Viewer3D/Sky.cs
Labels: enhancement

#306 Write back to the settings store on quit
  Source/ORTS.Settings/UserSettings.cs
  Source/RunActivity/Program.cs
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/Commands.cs
  Source/RunActivity/Viewer3D/Popups/OSDCars.cs
  Source/RunActivity/Viewer3D/Popups/OSDLocations.cs
  Source/RunActivity/Viewer3D/Popups/TrackMonitorWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#340 Create C# signalling scripting interface
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/operation.rst
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Common/Scripting/Common.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/AbstractPowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/CircuitBreaker.cs
  Source/Orts.Simulation/Common/Scripting/ScriptManager.cs
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Signalling/CsSignalScript.cs
  Source/Orts.Simulation/Simulation/Signalling/CsSignalScripts.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
Labels: enhancement

#365 Update AI horn blow sections in the manual
  Source/Documentation/Manual/operation.rst
Labels: documentation

#367 Resolve Monogame build warnings
  Source/Orts.Simulation/Simulation/Activity.cs
  Source/RunActivity/Viewer3D/DynamicTrack.cs
  Source/RunActivity/Viewer3D/Lights.cs
  Source/RunActivity/Viewer3D/MSTSSky.cs
  Source/RunActivity/Viewer3D/ParticleEmitter.cs
  Source/RunActivity/Viewer3D/Popups/Window.cs
  Source/RunActivity/Viewer3D/Precipitation.cs
  Source/RunActivity/Viewer3D/Shapes.cs
  Source/RunActivity/Viewer3D/Sky.cs
  Source/RunActivity/Viewer3D/SuperElevation.cs
  Source/RunActivity/Viewer3D/Terrain.cs
  Source/RunActivity/Viewer3D/Transfers.cs
  Source/RunActivity/Viewer3D/Water.cs
  Source/RunActivity/Viewer3D/Wire.cs
Labels: refactoring

#371 Bug fix for https://bugs.launchpad.net/or/+bug/1917917 Turntable not turns in timetable mode.
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: bug

#374 Bug fix for ttps://bugs.launchpad.net/or/+bug/1918921 Crash after restore in timetable mode
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
Labels: bug

#357 Correct issues with diesel power not being applied correctly
  Source/Orts.Parsers.Msts/Interpolator.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/GearBox.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: bug

#368 Menu options help
  Source/Documentation/Manual/images/options-content.png
  Source/Documentation/Manual/images/options-evaluation.png
  Source/Documentation/Manual/images/options-general.png
  Source/Documentation/Manual/images/options-keyboard.png
  Source/Documentation/Manual/images/options-logger.png
  Source/Documentation/Manual/images/options-simulation.png
  Source/Documentation/Manual/images/options-updater.png
  Source/Documentation/Manual/options.rst
  Source/Menu/Menu.csproj
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/Menu/Properties/Resources.Designer.cs
  Source/Menu/Properties/Resources.resx
  Source/Menu/Resources/info-18-hover.png
  Source/Menu/Resources/info-18.png
Labels: documentation, enhancement

#363 Fix build warnings in the manual text
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/intro.rst
  Source/Documentation/Manual/physics.rst
  Source/Documentation/Manual/timetable.rst
Labels: documentation

#380 Fix operation.rst build warning
  Source/Documentation/Manual/operation.rst
Labels: documentation

#373 https://trello.com/c/Ek3wMQRs/484-enable-rotation-of-gauges-in-2d-cabs Enable inclined gauges in 2D cabs
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/images/cabs-gauges-rotation.png
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement

#382 Replace for loops with explicit array copies and comparisons
  Source/Orts.Formats.Msts/ShapeFile.cs
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: refactoring

#383 Add a video options setting for MultiSampleCount anti-aliasing
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/RunActivity/Viewer3D/Processes/RenderProcess.cs
Labels: enhancement

#376 Localize HUD brake information
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SingleTransferPipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
Labels: locales

#385 Bug fix for https://bugs.launchpad.net/or/+bug/1921615 No brake HUD after entering a new cab
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug
