Repository openrails/openrails, pull requests merged in 2021-04, with the labels that each got.

#386 Battery and PowerKey cab controls, on behalf of Paolo
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/sound.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#387 added 2 more activities for BNSF Scenic Route
  Website/openrails.org/learn/activities/index.php
Labels: website

#388 Save settings immediately upon changing in RunActivity.exe
  Source/ORTS.Common/SettingsBase.cs
  Source/ORTS.Settings/FolderSettings.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/ORTS.Settings/UpdateSettings.cs
  Source/ORTS.Settings/UpdateState.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/RunActivity/Program.cs
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/Popups/OSDCars.cs
  Source/RunActivity/Viewer3D/Popups/OSDLocations.cs
  Source/RunActivity/Viewer3D/Popups/TrackMonitorWindow.cs
  Source/RunActivity/Viewer3D/Popups/Window.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug

#390 Adds the signal ID and the aspect (including text aspect) of each signal head to the signalling debug window
  Source/RunActivity/Viewer3D/Popups/SignallingDebugWindow.cs
Labels: enhancement

#394 Bug fix for https://bugs.launchpad.net/or/+bug/1923946 Variable2 goes negative with electric locos
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSElectricLocomotive.cs
Labels: bug

#393 Bug fix for https://bugs.launchpad.net/or/+bug/1922480 Wrong subpath selected after join and split
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: bug

#397 Webserver API/TIME
  Source/Documentation/Manual/images/web-page-clock.png
  Source/Documentation/Manual/software-platform.rst
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/WebServices/Web/Time/flat_clock.html
  Source/RunActivity/Viewer3D/WebServices/Web/Time/index.css
  Source/RunActivity/Viewer3D/WebServices/Web/Time/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/Time/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/Time/shadow_clock.html
  Source/RunActivity/Viewer3D/WebServices/Web/Time/smooth_clock.html
  Source/RunActivity/Viewer3D/WebServices/Web/index.html
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
Labels: enhancement

#395 moved Help Icons in the Menu > Options > General tab to assist with translations
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
Labels: enhancement

#391 Animated wipers for 2D cabs, see http://www.elvastower.com/forums/index.php?/topic/34604-2d-cabs-wipers-animation/
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement
