Repository openrails/openrails, pull requests merged in 2021-01, with the labels that each got.

#330 Bug fix for https://bugs.launchpad.net/or/+bug/1909684 AI train speed variable not initialized
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
Labels: bug

#325 Fix invisible forest shadows: https://bugs.launchpad.net/or/+bug/1863217
  Source/RunActivity/Viewer3D/Shaders.cs
Labels: bug

#323 Add steam ejector visual effects
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
Labels: enhancement

#332 Bug fix for https://bugs.launchpad.net/or/+bug/1910154. Log File generates the same header warning message.
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
Labels: bug

#321 Improvements for EP and air braking systems
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/physics.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Common/Scripting/Common.cs
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/CircuitBreaker.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ElectricPowerSupply.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#333 Add tender mass initialization if values defined in WAG file
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: enhancement

#328 3 new banner images replace redundant ones
  Website/openrails.org/shared/banners/banner056.jpg
  Website/openrails.org/shared/banners/banner057.jpg
  Website/openrails.org/shared/banners/banner062.jpg
  Website/openrails.org/shared/banners/banner_list.csv
Labels: website

#331 Correct issues with brake cuts power in vacuum brakes
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
Labels: bug

#334 Bug fix for https://bugs.launchpad.net/or/+bug/1910684 Crash selecting height entry in altitude file
  Source/RunActivity/Viewer3D/Tiles.cs
Labels: bug

#335 Fix broken web track monitor API call and displays
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/WebServices/TrackMonitorDisplay.cs
  Source/RunActivity/Viewer3D/WebServices/TrainInfo.cs
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitor/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/TrackMonitorTrainDriving/index.js
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
Labels: bug

#341 Remove reference to parameter in manual not used
  Source/Documentation/Manual/physics.rst
Labels: bug

#344 Bug fix for https://bugs.launchpad.net/or/+bug/1912388 Crash with $attach and $detach in timetable mode
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
Labels: bug

#342 Bug fix for https://bugs.launchpad.net/or/+bug/1910746. By Buttercup.
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
Labels: bug
