Repository openrails/openrails, pull requests merged in 2021-11, with the labels that each got.

#522 Correct issue with tender water mass
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug

#519 Website changes for Release v1.4
  Website/openrails.org/contribute/developing-code/index.php
  Website/openrails.org/contribute/joining-the-team/index.php
  Website/openrails.org/discover/project-team/index.php
  Website/openrails.org/discover/version-1-4/index.php
  Website/openrails.org/download/changes/index.php
  Website/openrails.org/download/content/index.php
  Website/openrails.org/download/program/index.php
  Website/openrails.org/download/source/index.php
  Website/openrails.org/index.php
  Website/openrails.org/learn/faq/index.php
  Website/openrails.org/learn/faq/install.php
  Website/openrails.org/learn/manual-and-tutorials/index.php
  Website/openrails.org/share/community/index.php
  Website/openrails.org/share/gallery/index.php
  Website/openrails.org/share/gallery/title.php
  Website/openrails.org/shared/menu.php
  Website/openrails.org/shared/now_at_version_1_4.png
  Website/openrails.org/trade/index.php
Labels: website

#529 Replace manual cover image
  Source/Documentation/Manual/images/cover_image.png
Labels: documentation

#528 Updated link to Siskiyou Route site
  Website/openrails.org/learn/activities/index.php
Labels: website

#530 Steam adhesion not applied to all locomotives in the player train.
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#526 Bug fix for https://bugs.launchpad.net/or/+bug/1949292 AI train disappears after coupling and reversing
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
Labels: bug

#480 Blueprint https://blueprints.launchpad.net/or/+spec/digital-alignment-in-3dcabs
  Source/Documentation/Manual/cabs.rst
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement

#535 Correction of OR manual
  Source/Documentation/Manual/driving.rst
Labels: documentation

#536 Gently handle a track sound crash. Fixes bug https://bugs.launchpad.net/or/+bug/1754805
  Source/RunActivity/Viewer3D/Sound.cs
Labels: bug
