Repository openrails/openrails, pull requests merged in 2021-05, with the labels that each got.

#401 refactor(docs): New location for GitHub-related files
  Architecture/Architecture Diagram.url
  Architecture/CommandLog/ICommand.cs
  Architecture/CommandLog/ICommandLog.cs
  Architecture/CommandLog/IReceiver.cs
  Architecture/ContentData.cs
  Architecture/Messaging.cs
  Architecture/ORArchitecture.csproj
  Architecture/ORArchitecture.sln
  Architecture/Viewers.cs
  Architecture/iControlSignal.cs
  Architecture/iControlSwitches.cs
  Architecture/iControlTrain.cs
  Architecture/iVirtualWorld.cs
  Docs/Architecture.md
  Docs/Contributing.md
  Docs/Readme.md
Labels: documentation

#404 adds Design for Virtual Filesystem.md
  Docs/Design for Virtual Filesystem.md
Labels: documentation

#403 Updated French locales and templates
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/fr.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/fr.po
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/ORTS.Settings/fr.po
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/fr.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/fr.po
Labels: locales

#406 Update of the pt-PT menu locales. By Aldarion
  Source/Locales/Menu/pt-PT.po
Labels: locales

#402 Bug fix for https://bugs.launchpad.net/or/+bug/1922000. Train.CreateStationStop crash.
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: bug

#405 Bug fix for https://bugs.launchpad.net/or/+bug/1926983 Fog distance can't be initialized to value > 20000
  Source/RunActivity/Viewer3D/Weather.cs
Labels: bug

#411 Correct backslashes in docs
  Docs/Design for Virtual Filesystem.md
Labels: documentation, for-unstable

#415 It locales 1.4
  Source/Locales/Contrib/Contrib.pot
  Source/Locales/Contrib/it.po
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/it.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/Orts.Formats.OR/Orts.Formats.OR.pot
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/it.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/it.po
  Source/Locales/Updater/Updater.pot
Labels: locales

#409 Bug fix for https://bugs.launchpad.net/or/+bug/1927811 Dynamic weather not working
  Source/RunActivity/Viewer3D/Weather.cs
Labels: bug

#414 Fix issues with adhesion resume
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
Labels: bug

#413 Correct issue with wheels not rotating when simple control/physics is set
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: bug

#418 Fix index out of range bug in ETCS display
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ETCS/PlanningWindow.cs
Labels: bug
