Repository openrails/openrails, pull requests merged in 2021-07, with the labels that each got.

#422 Change alignment of couplers as they travel through curve.
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement

#431 Correct issue with motive force being reduced by braking force
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: bug

#436 added 4 missing sound triggers to manual
  Source/Documentation/Manual/sound.rst
Labels: documentation

#417 Animated Clocks recognized by ClockHands without extern Files
  Source/Documentation/Manual/features-route.rst
  Source/RunActivity/Viewer3D/Scenery.cs
Labels: enhancement, for-unstable, help wanted

#439 Bug fix for https://bugs.launchpad.net/or/+bug/1935997 Missing null check
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: bug

#441 Fix obstructed block for non-normal signal on a track circuit at the end of the track
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: bug

#433 Don't unload sound sources of the player train when camera near it
  Source/RunActivity/Viewer3D/Sound.cs
Labels: enhancement
