Repository openrails/openrails, pull requests merged in 2021-09, with the labels that each got.

#459 Russian locales for T1.3.1-1890 (testing) release
  Source/Locales/Contrib/ru.po
  Source/Locales/Menu/ru.po
  Source/Locales/ORTS.Common/ru.po
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/ru.po
Labels: locales

#457 Increase upper limit for World Object Density
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/ORTS.Settings/UserSettings.cs
Labels: enhancement, documentation

#449 Provides functionality for unpowered control car
  Source/Documentation/Manual/physics.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/ControlCarPowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/PowerSupply.cs
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSControlTrailerCar.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/RollingStock.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ControlCarPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: enhancement

#464 Bug fix for https://bugs.launchpad.net/or/+bug/1942061. WindResistance locales.
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: bug

#466 Bug fix for https://bugs.launchpad.net/or/+bug/1942652. Timetable crash.
  Source/RunActivity/Viewer3D/Popups/MultiPlayerWindow.cs
Labels: bug

#435 Revised installer for Release 1.4
  Build.cmd
  Source/Installer/Installer.iss
  Source/Installer/OpenRails from DVD/OpenRails from DVD.iss
  Source/Installer/OpenRails from download/OpenRails from download.iss
  Source/Installer/OpenRails shared/OpenRails.iss
  Source/Installer/OpenRails shared/Version.iss
  Source/Installer/Readme.txt
  Source/Installer/Using the installer scripts.txt
  Source/Installer/Version.iss
  Source/Launcher/Launcher.csproj
  Source/Launcher/Program.cs
  Source/Launcher/app.config
  Source/Menu/Menu.csproj
  Source/RunActivity/Prerequisites.txt
  Source/RunActivity/Readme.txt
  Source/RunActivity/RunActivity.csproj
Labels: refactoring

#465 feat: Add latest version information to registry
  Source/ORTS.Common/SettingsStore.cs
  Source/ORTS.Common/VersionInfo.cs
  Source/ORTS.Updater/UpdateManager.cs
Labels: enhancement

#468 Correct spelling error in manual, and missing setting of parameter
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: enhancement

#456 Further adjustment to airhose movement
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement

#470 Manual revision steam
  Source/Documentation/Manual/physics.rst
Labels: documentation

#467 Re-sequence Driving Aids sections in the Manual
  Source/Documentation/Manual/driving.rst
Labels: documentation

#462 Revised manual text for some options
  Source/Documentation/Manual/options.rst
Labels: documentation

#469 Correct an error introduced with braking enhamcement
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SMEBrakeSystem.cs
Labels: bug, enhancement

#471 Correct issue with control car wheels not rotating
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSControlTrailerCar.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug, enhancement

#476 fix: Allow official releases via GitHub
  Source/ORTS.Updater/UpdateManager.cs
Labels: bug

#477 Bug fix for https://bugs.launchpad.net/or/+bug/1943302 3D cab bugs in bars and digitals
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: bug

#478 Bug fix for https://bugs.launchpad.net/or/+bug/1943307 In 3d cabs Alert colour not displayed
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#479 Bug fix for https://bugs.launchpad.net/or/+bug/1943303 In 3D cabs bars ranging from negative to positive values are incorrectly displayed
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#482 Fix Toggle Player Engine command and refactor
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/LocomotivePowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/PowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/LocomotivePowerSupply.cs
Labels: bug, refactoring

#483 Update templates and French locales
  Source/Locales/Contrib/qps-ploc.po
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/fr.po
  Source/Locales/Menu/qps-ploc.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/fr.po
  Source/Locales/ORTS.Common/qps-ploc.po
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/ORTS.Settings/fr.po
  Source/Locales/ORTS.Settings/qps-ploc.po
  Source/Locales/Orts.Formats.OR/qps-ploc.po
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/fr.po
  Source/Locales/Orts.Simulation/qps-ploc.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/fr.po
  Source/Locales/RunActivity/qps-ploc.po
Labels: locales

#485 Fix pantograph 1 raise confirmation message
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Pantograph.cs
Labels: bug

#486 Bug fix for https://bugs.launchpad.net/or/+bug/1943837 3D cabs: digitals aren't clamped against Max and MinValue
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#484 fix: Do not act recursively on documentation or things go wrong
  Build.cmd
Labels: infrastructure

#489 Manual Software Platform
  Build.cmd
  Source/Documentation/Manual/software-platform.rst
Labels: documentation

#491 Announce train driving window
  Source/Documentation/Manual/news.rst
  Website/openrails.org/discover/version-1-4/index.php
  Website/openrails.org/discover/version-1-4/title.php
Labels: documentation

#494 adds Folders Used By OR to manual appendix
  Source/Documentation/Manual/appendices.rst
Labels: documentation

#495 Fixed a mistake in SignalEventToHelperEngines
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/LocomotivePowerSupply.cs
Labels: bug

#497 Bug fix for https://bugs.launchpad.net/or/+bug/1944725 Switching 3D cab the camera position is incorrect
  Source/RunActivity/Viewer3D/Cameras.cs
Labels: bug

#502 Correct issue with mechanical compressors not showing in HuD
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: bug

#498 Fixed wrong integer values for cabview controls related to power supplies
  Source/Orts.Simulation/Common/Scripting/PowerSupply/CircuitBreaker.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/PowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/TractionCutOffRelay.cs
Labels: bug

#505 Set compressor to only operate on electric compressor code for v1.4
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug
