Repository openrails/openrails, pull requests merged in 2021-12, with the labels that each got.

#534 deletes RunActivityLAA.* post-build
  Source/RunActivity/RunActivity.csproj
Labels: enhancement

#540 Correct issue created in timetable mode
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug

#539 Correct starting tractive force of steam locomotive
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#532 Distributed power american style. Blueprint https://blueprints.launchpad.net/or/+spec/distributed-power
  Source/Documentation/Manual/images/physics-dpu-window.png
  Source/Documentation/Manual/physics.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/LocomotivePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Popups/CarOperationsWindow.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainDPUWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
  Source/RunActivity/Viewer3D/Popups/WindowControls.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#538 Delete binary paths if the ascii version or the tdb was modified. Blueprint: https://blueprints.launchpad.net/or/+spec/binary-timetable-paths
  Source/Documentation/Manual/timetable.rst
  Source/Orts.Formats.Msts/TrackDatabaseFile.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
Labels: enhancement, not-for-unstable

#531 Bug fix for https://bugs.launchpad.net/or/+bug/1950578 Dyn Brake setup state not disappearing in cab
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#544 Blueprint https://blueprints.launchpad.net/or/+spec/cabview-controls-for-generic-items
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/sound.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Formats.Msts/ShapeDescriptorFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
  Source/RunActivity/Viewer3D/Shapes.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#546 Blueprint https://blueprints.launchpad.net/or/+spec/multiple-screen-pages in 2D and 3D cabs
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/RunActivity/Viewer3D/Commands.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Shapes.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#549 Generic items: optional internal 3DCab animation linked to them
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement

#547 Add support for dual-screen ETCS DMI
  Source/Documentation/Manual/options.rst
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ETCS/DriverMachineInterface.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ETCS/TextMessages.cs
Labels: enhancement

#550 Adjust diesel fuel consumption
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
Labels: bug

#552 Fix out of range index when changing cabs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug

#548 Links to dead Siskiyou site removed
  Website/openrails.org/index.php
  Website/openrails.org/learn/activities/index.php
Labels: website

#558 Revised Visual Studio version
  Website/openrails.org/contribute/developing-code/index.php
Labels: website

#543 adds Discover > Roadmap webpage
  Website/openrails.org/discover/roadmap/index.php
  Website/openrails.org/discover/roadmap/title.php
  Website/openrails.org/discover/was-our-plans/index.php
  Website/openrails.org/discover/was-our-plans/title.php
  Website/openrails.org/shared/menu.php
Labels: website

#542 adds new webpage, moves Testing out of Download/Programs
  Website/openrails.org/download/program/index.php
  Website/openrails.org/download/versions/3_versions.png
  Website/openrails.org/download/versions/improvements.png
  Website/openrails.org/download/versions/index.php
  Website/openrails.org/download/versions/title.php
  Website/openrails.org/download/versions/update_link.png
  Website/openrails.org/download/versions/updater_tab.png
  Website/openrails.org/shared/menu.php
Labels: website
