Repository openrails/openrails, pull requests merged in 2021-08, with the labels that each got.

#443 CVCDiscrete extended to report correct MaxValue
  Source/Orts.Formats.Msts/CabViewFile.cs
Labels: bug

#408 Updating RailDriver SDK library to prepare for 64bit mode
  Source/3rdPartyLibs/PIEHidDotNet.dll
  Source/Launcher/Program.cs
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/UserInputRailDriver.cs
  Source/RunActivity/packages.config
Labels: refactoring

#412 New TCS function to get speed post information (including warning speed posts)
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/Orts.Simulation/Simulation/Signalling/SpeedPostWorldObject.cs
  Source/RunActivity/Viewer3D/Popups/TrackMonitorWindow.cs
Labels: enhancement

#421 Added a reset command in order to reset a TCS emergency braking triggered by the simulator
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/features-rollingstock.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#442 Correct input discrepancy for tractive force tables
  Source/Orts.Parsers.Msts/Interpolator.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
Labels: bug

#446 Fix for Copy function not being called in ScriptedDieselPowerSupply and ScriptedElectricPowerSupply
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DualModePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ElectricPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/LocomotivePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/SteamPowerSupply.cs
Labels: bug

#448 Bug fix for https://bugs.launchpad.net/or/+bug/1939064. Web-HUD label is not displayed.
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/WebServices/Web/HUD/index.html
Labels: bug

#450 Bug fix for https://bugs.launchpad.net/or/+bug/1939995 DynamicBrakeAvailable not copied to further loco instances
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#440 Addition of Derail Coefficient and further coupler animation
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement

#447 Minor adjustments to number of wheels checking
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug

#451 Fixed the wrong states of battery switch, master key and ETS switch after restoring from a save
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/BatterySwitch.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ElectricTrainSupplySwitch.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/MasterKey.cs
Labels: bug

#452 Fix : Passenger car power supply should not be available for locomotives
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: bug

#453 Fix tractive force not equal to zero during emergency braking
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
Labels: bug

#454 Fix NaN values for diesel output power and load during engine shut-down
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
Labels: bug

#455 Fix mismatch between saved and restored values in PassengerCarPowerSupply and added missing values
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/PassengerCarPowerSupply.cs
Labels: bug

#458 Added .timetable-or file extension in the timetable editor
  Source/Contrib/TimetableEditor/unit1.lfm
  Source/Contrib/TimetableEditor/unit1.pas
Labels: bug

#445 Add a PreUpdate variable to scripts
  Source/Orts.Simulation/Common/Scripting/Common.cs
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/CircuitBreaker.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/LocomotivePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/PassengerCarPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/TractionCutOffRelay.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Signalling/CsSignalScript.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTurntable.cs
Labels: enhancement
