Repository openrails/openrails, pull requests merged in 2022-11, with the labels that each got.

#742 Update of Russian Locales 'Oct 2022
  Source/Locales/Menu/ru.po
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/ru.po
Labels: for-unstable, locales

#630 Sky Color Fix (Addresses Trello Roadmap Card #367 for More accurate sunrise and sunset)
  Source/RunActivity/Content/ParticleEmitterShader.fx
  Source/RunActivity/Content/SkyShader.fx
Labels: enhancement, good first issue, for-unstable

#736 Replaced truncated brake token table with lists
  Source/Documentation/Manual/physics.rst
Labels: bug, documentation

#743 Default filename for include statements
  Source/Documentation/Manual/physics.rst
  Source/Orts.Parsers.Msts/STFReader.cs
Labels: enhancement

#745 Fix digital displays in rear 3D cab
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#713 https://blueprints.launchpad.net/or/+spec/cruise-control
  Source/Documentation/Manual/cruisecontrol.rst
  Source/Documentation/Manual/images/cruisecontrol-mainhud.png
  Source/Documentation/Manual/images/cruisecontrol-samplecab.png
  Source/Documentation/Manual/images/cruisecontrol-traindriverwindow.png
  Source/Documentation/Manual/index.rst
  Source/Documentation/SampleFiles/Manual/E652_CC.zip
  Source/Documentation/SampleFiles/Manual/FS_E652_143MIR.zip
  Source/Documentation/SampleFiles/Manual/Fs-E464-390.zip
  Source/Documentation/SampleFiles/Manual/e464_V2SCMT_SCMTscript_alias_CC.zip
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MultiPositionController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/CruiseControlViewer.cs
Labels: enhancement

#741 Fixed brake controller script not being loaded in timetable mode
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
Labels: bug

#734 Fixed battery switch timer not working properly
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/BatterySwitch.cs
Labels: bug

#733 Fixed battery switch sound being repeted
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/BatterySwitch.cs
Labels: bug
