Repository openrails/openrails, pull requests merged in 2022-04, with the labels that each got.

#634 Out of range exception with >= 256 cab controls
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#615 Management of EOT devices https://blueprints.launchpad.net/or/+spec/eot
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/images/physics-eot-display.png
  Source/Documentation/Manual/images/physics-eot.png
  Source/Documentation/Manual/physics.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/ActivityFile.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Scripting/Common.cs
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/RollingStock.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/EOT.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Popups/EOTListWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#636 Remove venting of MRP because conflicts with EOT
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: bug

#633 Removed ViewDispatcher setting
  Source/ORTS.Settings/UserSettings.cs
  Source/RunActivity/Viewer3D/Processes/GameStateViewer3D.cs
Labels: bug

#631 Get correct signal id if signal ahead is in same Track Circuit
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: bug

#622 Bug fix for https://bugs.launchpad.net/or/+bug/1965311. TDI: The vacuum brake value is misaligned.
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
Labels: bug

#637 Bug fix for http://www.elvastower.com/forums/index.php?/topic/36129-player-trainlead-locomotive-must-be-player-locomotive-crash/
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
Labels: bug

#638 Update es.po (menu)
  Source/Locales/Menu/es.po
Labels: locales

#613 fix: Use properly FPS-independent smoothing function
  Source/ORTS.Common/SmoothedData.cs
  Source/Tests/Orts.Common/SmoothedData.cs
  Source/Tests/Tests.csproj
Labels: enhancement

#635 Minor steam locomotive issues.
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#643 Brake controller buttons are not animated
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#620 Adjust kinietic friction calculations
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#616 Improvements in graduated/full release braking
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirTwinPipe.cs
Labels: enhancement

#619 Adjust HuD to display relevant parameters for DM locomotive
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: enhancement
