Repository openrails/openrails, pull requests merged in 2022-08, with the labels that each got.

#525 TCS extensions
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: enhancement

#672 Calculate distance to signal in explorer mode
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: bug

#673 hu locales update
  Source/Locales/Contrib/hu.po
  Source/Locales/Menu/hu.po
  Source/Locales/ORTS.Common/hu.po
  Source/Locales/ORTS.Menu/hu.po
  Source/Locales/Orts.Simulation/hu.po
  Source/Locales/RunActivity/hu.po
Labels: for-unstable, locales

#674 Mark particle drawer texture for wagons
  Source/RunActivity/Viewer3D/ParticleEmitter.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: bug

#665 02n: Removes some redundant experimental options
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/RunActivity/Viewer3D/Common/Helpers.cs
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
Labels: enhancement

#671 Updates manual for Release 1.5
  Source/Documentation/Manual/images/cover_image.png
  Source/Documentation/Manual/news.rst
Labels: documentation

#676 adds content hosted on GitHub.com
  Website/openrails.org/contribute/building-models/index.php
  Website/openrails.org/download/content/index.php
  Website/openrails.org/index.php
Labels: website

#682 Updated links to Deco Games
  Website/openrails.org/download/content/index.php
  Website/openrails.org/trade/index.php
Labels: website

#680 build: Fix the file metadata after the .NET SDK project switch
  Source/ContentChecker/ContentChecker.csproj
  Source/Contrib/ActivityEditor/ActivityEditor/ActivityEditor.csproj
  Source/Contrib/ActivityEditor/LibAE/LibAE.csproj
  Source/Contrib/ContentManager/ContentManager.csproj
  Source/Contrib/DataCollector/DataCollector.csproj
  Source/Contrib/DataConverter/DataConverter.csproj
  Source/Contrib/DataValidator/DataValidator.csproj
  Source/Contrib/SimulatorTester/SimulatorTester.csproj
  Source/Contrib/TimetableEditor/timetableedit.lpi
  Source/Contrib/TrackViewer/TrackViewer.csproj
  Source/Launcher/Launcher.csproj
  Source/Menu/Menu.csproj
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Content/ORTS.Content.csproj
  Source/ORTS.IO/ORTS.IO.csproj
  Source/ORTS.Menu/ORTS.Menu.csproj
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Updater/ORTS.Updater.csproj
  Source/Orts.Formats.Msts/Orts.Formats.Msts.csproj
  Source/Orts.Formats.OR/Orts.Formats.OR.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.OR/Orts.Parsers.OR.csproj
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/RunActivity/RunActivity.csproj
  Source/Tests/Tests.csproj
  Source/Updater/Updater.csproj
Labels: infrastructure

#683 fix: Clean up Simulator Tester help output to match dotnet-style
  Source/Contrib/SimulatorTester/Program.cs
Labels: bug

#687 fix: Clean up Content Checker help output to match dotnet-style
  Source/ContentChecker/Program.cs
Labels: bug

#681 test: Fix tests when StfReader tests run before JsonReader tests
  Source/Tests/AssertWarnings.cs
  Source/Tests/Orts.Parsers.OR/JsonReaderTests.cs
Labels: bug

#675 Bug fix for https://bugs.launchpad.net/or/+bug/1983511 When an AI train disappears at end of run, containers remain visible
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/FreightAnimations.cs
Labels: bug

#679 Provide travelled distance to TCS scripts taking into account the running direction
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
Labels: enhancement

#537 C# signal script extensions
  Source/ContentChecker/SignalScriptLoader.cs
  Source/Contrib/TrackViewer/Drawing/DrawableTrackItem.cs
  Source/Documentation/Manual/appendices.rst
  Source/Orts.Formats.Msts/SignalConfigurationFile.cs
  Source/Orts.Formats.Msts/SignalScripts.cs
  Source/Orts.Formats.OR/AESignals.cs
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Signalling/CrossOverItem.cs
  Source/Orts.Simulation/Simulation/Signalling/CsSignalScript.cs
  Source/Orts.Simulation/Simulation/Signalling/DeadlockInfo.cs
  Source/Orts.Simulation/Simulation/Signalling/DeadlockPathInfo.cs
  Source/Orts.Simulation/Simulation/Signalling/Milepost.cs
  Source/Orts.Simulation/Simulation/Signalling/ObjectItemInfo.cs
  Source/Orts.Simulation/Simulation/Signalling/ObjectSpeedInfo.cs
  Source/Orts.Simulation/Simulation/Signalling/PlatformDetails.cs
  Source/Orts.Simulation/Simulation/Signalling/SIGSCRfile.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalHead.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalObject.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalRefObject.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalWorldObject.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/Orts.Simulation/Simulation/Signalling/TrackCircuitItems.cs
  Source/Orts.Simulation/Simulation/Signalling/TrackCircuitMilepost.cs
  Source/Orts.Simulation/Simulation/Signalling/TrackCircuitSection.cs
  Source/Orts.Simulation/Simulation/Signalling/TrackCircuitSignalItem.cs
  Source/Orts.Simulation/Simulation/Signalling/TrackCircuitSignalList.cs
  Source/Orts.Simulation/Simulation/Signalling/TrackCircuitState.cs
  Source/Orts.Simulation/Simulation/Signalling/TrainOccupyState.cs
  Source/Orts.Simulation/Simulation/Signalling/TrainQueue.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
  Source/RunActivity/Viewer3D/Debugging/TimetableWindow.cs
  Source/RunActivity/Viewer3D/Popups/SignallingDebugWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrackMonitorWindow.cs
  Source/RunActivity/Viewer3D/Signals.cs
Labels: enhancement, refactoring

#678 Refactor TrainCar part 1
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/Coupling/AnimatedAirHose.cs
  Source/Orts.Simulation/Simulation/RollingStocks/Coupling/AnimatedCoupler.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: refactoring

#686 fix: Clean up Data Collector help output to match dotnet-style
  Source/Contrib/DataCollector/Program.cs
Labels: bug

#685 fix: Clean up Data Converter help output to match dotnet-style
  Source/Contrib/DataConverter/Program.cs
Labels: bug

#684 fix: Clean up Data Validator help output to match dotnet-style
  Source/Contrib/DataValidator/Program.cs
Labels: bug

#696 Add check to prevent crashes when signal scripts use a bad draw state
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
Labels: bug

#695 Container loaded wagons in Multiplayer mode
  Source/Orts.Simulation/MultiPlayer/MPManager.cs
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/MultiPlayer/OnlineTrains.cs
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/Container.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/FreightAnimations.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ContainerViewer.cs
Labels: enhancement

#691 Removed lines in the RunActivity project file that are no longer used
  Source/RunActivity/RunActivity.csproj
Labels: bug

#700 Fix for crash during signal loading
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalObject.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/Orts.Simulation/Simulation/Signalling/SpeedPostWorldObject.cs
Labels: bug

#667 Fix typo in Czech translation of menu
  Source/Locales/Menu/cs.po
Labels: for-unstable, locales

#703 Add default signal function in case of SIGCFG errors
  Source/Orts.Simulation/Simulation/Signalling/SignalHead.cs
Labels: bug
