Repository openrails/openrails, pull requests merged in 2022-07, with the labels that each got.

#666 Website - correction to link for unstable versions
  Website/openrails.org/download/versions/index.php
Labels: website

#658 style: Add .NET editorconfig from Visual Studio templates
  Source/.editorconfig
Labels: infrastructure

#659 Bug fix for https://bugs.launchpad.net/or/+bug/1979824 Seconds in digital clock within 3Dcab not displayed
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#656 Bug fix for https://bugs.launchpad.net/or/+bug/1979005 Drive wheels not rotating at correct speed
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: bug

#661 Corrected text that had become out of date
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/physics.rst
Labels: documentation

#663 Restores option 02g removed in PR#589
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: bug

#670 adds Help Icons to Audio options tab (again)
  Source/Documentation/Manual/images/options-audio.png
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/Menu/Options.resx
Labels: enhancement, documentation
