Repository openrails/openrails, pull requests merged in 2022-10, with the labels that each got.

#716 Bug fix for https://bugs.launchpad.net/or/+bug/1990553 Typo in GenericItem2 command
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#693 French locales
  Source/Locales/Contrib/Contrib.pot
  Source/Locales/Contrib/fr.po
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/fr.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/fr.po
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/fr.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/fr.po
Labels: locales

#723 Fix for default texture being added multiple times in Textures list
  Source/RunActivity/Viewer3D/Materials.cs
Labels: bug

#721 Do not trigger wheelslip alarm until some time passes
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
Labels: bug

#712 Search for NORMAL signals if no argument is provided
  Source/Orts.Formats.Msts/SignalScripts.cs
  Source/Orts.Simulation/Simulation/Signalling/SIGSCRfile.cs
Labels: bug

#699 Bug fix for https://bugs.launchpad.net/or/+bug/1987453. Web: HUD/Force Information, some labels not visible.
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/WebServices/Web/HUD/index.js
Labels: bug

#692 Italian translation for OR 1.5
  Source/Locales/Menu/it.po
  Source/Locales/ORTS.Common/it.po
  Source/Locales/ORTS.Menu/it.po
  Source/Locales/Orts.Simulation/it.po
  Source/Locales/RunActivity/it.po
Labels: locales

#728 Bug fix for https://bugs.launchpad.net/or/+bug/1992301 World becoming fully dark
  Source/RunActivity/Viewer3D/Common/SunMoonPos.cs
Labels: bug

#726 Fix brake initialization problems
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: bug

#731 fix: Log first error during Viewer mark-sweep clean-up
  Source/RunActivity/Viewer3D/World.cs
Labels: bug

#677 Correct double heading bug
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/GearBox.cs
Labels: bug, enhancement
