Repository openrails/openrails, pull requests merged in 2022-03, with the labels that each got.

#591 02i: Removed menu option ConditionalLoadOfDayOrNightTextures. Now always conditional.
  Source/Documentation/Manual/images/options-experimental.png
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/Menu/Options.resx
  Source/ORTS.Settings/UserSettings.cs
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/Scenery.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement, documentation

#592 02j: Removed menu option ViewDispatcher . Now always available.
  Source/Documentation/Manual/images/options-dispatcher.png
  Source/Documentation/Manual/images/options-general.png
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
Labels: enhancement, documentation

#598 02k: Removed menu option Override non-electrified route line-voltage
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSElectricLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DualModePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ElectricPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Pantograph.cs
Labels: enhancement, documentation

#603 Bug fix for https://bugs.launchpad.net/or/+bug/1961304. HUD - DPI extended page, misaligned.
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: bug

#614 Initialize EP and twin pipe brakes to correct pressure
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
Labels: bug

#602 New model for MR pipe air propagation
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
Labels: bug, refactoring

#593 Initial Diesel Mechanic Locomotive Simulation
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Common/Scripting/PowerSupply/PowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/GearBox.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: enhancement

#606 Bug fix for http://www.elvastower.com/forums/index.php?/topic/36021-crash-on-switching-to-autopilot/#entry282465
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
Labels: bug

#607 Building instructions for developers
  Docs/Building.md
  Docs/images/add_demo_model_1.png
  Docs/images/add_vs_extension.png
  Docs/images/authorising_visual_studio_installer.png
  Docs/images/build_html_manual.png
  Docs/images/build_projects.png
  Docs/images/cloning_repo.png
  Docs/images/configure_visual_studio_installer.png
  Docs/images/copy_arguments.png
  Docs/images/debug_project.png
  Docs/images/download_docker_desktop.png
  Docs/images/download_wsl_2.png
  Docs/images/downloading_repo.png
  Docs/images/downloading_visual_studio_installer.png
  Docs/images/enable_virtual_machine.png
  Docs/images/enable_virtual_machine_feature.png
  Docs/images/executable_files.png
  Docs/images/find_manual_folder.png
  Docs/images/find_vsc_commands.png
  Docs/images/framework_not_installed.png
  Docs/images/html_manual.png
  Docs/images/install_remote_containers.png
  Docs/images/install_wsl_2.png
  Docs/images/installation_profiles.png
  Docs/images/launching_runactivity.png
  Docs/images/manual_file_list.png
  Docs/images/menu_option_content.png
  Docs/images/open_rails_projects.png
  Docs/images/orts_solution.png
  Docs/images/pdf_manual.png
  Docs/images/progress_for_docker_desktop.png
  Docs/images/prompt_from_visual_studio_installer.png
  Docs/images/restart_docker_desktop.png
  Docs/images/run_powershell.png
  Docs/images/run_visual_studio_installer.png
  Docs/images/search_for_remote_containers.png
  Docs/images/settings_for_docker_desktop.png
  Docs/images/sign_in_to_microsoft.png
  Docs/images/start_activity.png
  Docs/images/start_visual_studio.png
  Docs/images/startup_project.png
  Docs/images/successful_build.png
  Docs/images/unzip_demo_model_1.png
  Docs/images/wsl2_for_docker_desktop.png
Labels: documentation

#611 docs: Current threading and object/class architecture
  Docs/Architecture.md
Labels: documentation

#612 https://blueprints.launchpad.net/or/+spec/distributed-power-display-for-3d-cabs
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/images/cabs-dpi-ace.png
  Source/Documentation/SampleFiles/Manual/DPI.zip
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/DistributedPowerInterface.cs
Labels: enhancement

#594 ScriptManager migration to the CodeAnalysis class. This is in preparation for the net 6 migration.
  Source/Orts.Simulation/Common/Scripting/ScriptManager.cs
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/packages.config
Labels: refactoring

#618 added web-server firewall to Manual
  Source/Documentation/Manual/images/firewall.png
  Source/Documentation/Manual/options.rst
  Source/Documentation/Manual/software-platform.rst
  Source/Documentation/Manual/start.rst
Labels: documentation

#621 Correct Maximum Tractive Effort
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#623 Russian localization for T 1.4-413 version
  Source/Contrib/TimetableEditor/languages/contrib.timetableeditor.ru.po
  Source/Locales/Menu/ru.po
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/ru.po
Labels: locales

#626 Timetable loading bar added
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/images/loading_bars.png
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
Labels: enhancement
