Repository openrails/openrails, pull requests merged in 2022-09, with the labels that each got.

#701 Prevent train from going to manual mode from an explorer activity
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalObject.cs
Labels: bug

#702 Bug fix for https://bugs.launchpad.net/or/+bug/1987504 Server can't throw switches for clients in multiplayer
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
Labels: bug

#690 Sync turntables and transfertables in multiplayer mode
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Transfertables.cs
  Source/Orts.Simulation/Simulation/Turntables.cs
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: enhancement

#705 feat: Updated Russian translations
  Source/Locales/Contrib/ru.po
  Source/Locales/Menu/ru.po
  Source/Locales/ORTS.Common/ru.po
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/ru.po
Labels: locales

#707 fix: Add help option to help output of Data Collector
  Source/Contrib/DataCollector/Program.cs
Labels: bug

#708 fix: Add help option to help output of Data Converter
  Source/Contrib/DataConverter/Program.cs
Labels: bug

#709 fix: Add help option to help output to Data Validator
  Source/Contrib/DataValidator/Program.cs
Labels: bug

#710 Fix GetDrawState when using upper characters in the name parameter
  Source/Orts.Simulation/Simulation/Signalling/CsSignalScript.cs
Labels: bug

#711 Bug fix for https://bugs.launchpad.net/or/+bug/1989426 Out of bounds crash in Precipitation.cs
  Source/RunActivity/Viewer3D/Precipitation.cs
Labels: bug

#688 adds Help Icons to Video tab
  Source/Documentation/Manual/images/options-experimental.png
  Source/Documentation/Manual/images/options-video.png
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/Menu/Options.resx
Labels: enhancement, documentation
