Repository openrails/openrails, pull requests merged in 2022-02, with the labels that each got.

#576 DaylightOffsetHrs control: Fix for offset not effective soon after midnight
  Source/RunActivity/Viewer3D/MSTSSky.cs
  Source/RunActivity/Viewer3D/Sky.cs
Labels: bug

#533 fix for shapes hidden by animations( 0 )
  Source/RunActivity/Viewer3D/Scenery.cs
Labels: bug

#524 Further strings translation
  Source/Locales/Contrib/ru.po
  Source/Locales/Menu/ru.po
  Source/Locales/ORTS.Common/ru.po
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/ru.po
Labels: locales

#578 https://bugs.launchpad.net/or/+bug/1959084 Wrong locale file IDs for pt-PT and pt-BR
  Source/Locales/Contrib/pt-BR.po
  Source/Locales/Menu/pt-BR.po
  Source/Locales/ORTS.Common/pt-BR.po
  Source/Locales/ORTS.Menu/pt-BR.po
  Source/Locales/ORTS.Menu/pt-PT.po
  Source/Locales/ORTS.Settings/pt-BR.po
  Source/Locales/Orts.Formats.OR/pt-BR.po
  Source/Locales/Orts.Simulation/pt-BR.po
  Source/Locales/RunActivity/pt-BR.po
  Source/Locales/Updater/pt-BR.po
Labels: bug

#582 Bug fix for https://bugs.launchpad.net/or/+bug/1959617 Positive bars can't have two colours
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#583 Bug fix for https://bugs.launchpad.net/or/+bug/1959660 Glitch in ORTS_SIGNED_TRACTION_BRAKING
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#579 Fix for https://bugs.launchpad.net/or/+bug/1959336.
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
Labels: bug

#545 Fix VRAM usage
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/FreightAnimationsViewer.cs
  Source/RunActivity/Viewer3D/Shapes.cs
  Source/RunActivity/Viewer3D/Signals.cs
  Source/RunActivity/Viewer3D/Viewer.cs
  Source/RunActivity/Viewer3D/World.cs
Labels: bug

#595 Release locomotive brake when player train enters game with speed > 0
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#564 Added TCS parameters file path in consist files (+ refactoring and code cleanup)
  Source/Orts.Formats.Msts/ActivityFile.cs
  Source/Orts.Simulation/MultiPlayer/MPManager.cs
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/MultiPlayer/OnlineTrains.cs
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/RollingStock.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
Labels: enhancement, refactoring

#584 02a: Removed option MSTSBin. Its sound events are now permanently active.
  Source/Documentation/Manual/images/options-audio.png
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/Orts.Simulation/Common/Events.cs
Labels: enhancement, documentation

#597 Bug fix for http://www.elvastower.com/forums/index.php?/topic/35981-walking-people-dont-walk-well/
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: bug

#601 Video-RAM message to logfile fails under VMWare
  Source/ORTS.Common/SystemInfo.cs
Labels: bug

#600 fix: Store DirectX feature level as the enum internally for performance
  Source/ORTS.Settings/UserSettings.cs
Labels: bug

#571 01: Manual entries for Menu > Options corrected
  Source/Documentation/Manual/options.rst
Labels: enhancement

#596 Fix for https://bugs.launchpad.net/or/+bug/1960519. Crash, diesel locomotive with vacuum brakes.
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/RunActivity/Viewer3D/Popups/TrainDPUWindow.cs
Labels: bug

#561 Manual call-on is reset when passing an advanced signal - https://bugs.launchpad.net/or/+bug/1955907
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
Labels: bug

#580 SamplerStates can only be set after the ShaderPasses.Current.Apply().
  Source/RunActivity/Viewer3D/Forest.cs
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/Terrain.cs
  Source/RunActivity/Viewer3D/Transfers.cs
  Source/RunActivity/Viewer3D/Water.cs
Labels: bug

#581 Blueprint https://blueprints.launchpad.net/or/+spec/traindpuinfo-web-server
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/WebServices/TrainDpuDisplay.cs
  Source/RunActivity/Viewer3D/WebServices/Web/TrainDpu/index.css
  Source/RunActivity/Viewer3D/WebServices/Web/TrainDpu/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/TrainDpu/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/arrow_down.png
  Source/RunActivity/Viewer3D/WebServices/Web/arrow_left.png
  Source/RunActivity/Viewer3D/WebServices/Web/arrow_right.png
  Source/RunActivity/Viewer3D/WebServices/Web/arrow_up.png
  Source/RunActivity/Viewer3D/WebServices/Web/index.html
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
Labels: enhancement

#608 Copy DynamicBrakeMaxCurrentA to replicas of same locomotive
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#605 Fix problem when curve speed dependent not selected
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: bug

#567 Adds 64-bit compatibility
  Build.cmd
  Source/ContentChecker/ContentChecker.csproj
  Source/Contrib/ActivityEditor/AEWizard/AEWizard.csproj
  Source/Contrib/ActivityEditor/ActivityEditor/ActivityEditor.csproj
  Source/Contrib/ActivityEditor/LibAE/LibAE.csproj
  Source/Contrib/ContentManager/ContentManager.csproj
  Source/Contrib/DataCollector/DataCollector.csproj
  Source/Contrib/DataConverter/DataConverter.csproj
  Source/Contrib/DataValidator/DataValidator.csproj
  Source/Contrib/TrackViewer/Drawing/CloseToMouse.cs
  Source/Contrib/TrackViewer/Drawing/DrawArea.cs
  Source/Contrib/TrackViewer/Drawing/DrawTrackDB.cs
  Source/Contrib/TrackViewer/Drawing/Labels/DrawLabels.cs
  Source/Contrib/TrackViewer/Editing/PathEditor.cs
  Source/Contrib/TrackViewer/Editing/TrainpathNode.cs
  Source/Contrib/TrackViewer/TrackViewer.csproj
  Source/Documentation/Manual/images/options-general.png
  Source/Documentation/Manual/options.rst
  Source/Menu/MainForm.cs
  Source/Menu/Menu.csproj
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Common/Coordinates.cs
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Menu/ORTS.Menu.csproj
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Updater/ORTS.Updater.csproj
  Source/ORTS.sln
  Source/Orts.Formats.Msts/Orts.Formats.Msts.csproj
  Source/Orts.Formats.OR/Orts.Formats.OR.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.OR/Orts.Parsers.OR.csproj
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
  Source/RunActivity/Viewer3D/OpenAL.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Viewer.cs
  Source/Tests/Tests.csproj
  Source/Updater/Updater.csproj
Labels: enhancement
