Repository openrails/openrails, pull requests merged in 2022-01, with the labels that each got.

#563 Correct a timing issue in Eames brakes
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/StraightVacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
Labels: bug

#557 Add support for the building the manual with a Visual Studio Code development container
  Source/Documentation/Manual/.devcontainer/Dockerfile
  Source/Documentation/Manual/.devcontainer/devcontainer.json
  Source/Documentation/Manual/.vscode/tasks.json
Labels: documentation, infrastructure

#556 Improve memory statistics for CPU and GPU
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/images/driving-hud-debug-graphs.png
  Source/Documentation/Manual/images/driving-hud-debug.png
  Source/Launcher/app.manifest
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: enhancement

#554 Bug fix for Crash when switching cabs and changing screen page https://bugs.launchpad.net/or/+bug/1955575
  Source/RunActivity/Viewer3D/Commands.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug

#566 Fix for https://bugs.launchpad.net/or/+bug/1956262. F5 causes OR crash.
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
Labels: bug

#551 Make handling the timetable-or extension consistent.
  Source/ContentChecker/TrackFileLoader.cs
  Source/Contrib/ContentManager/ContentMSTS.cs
  Source/Contrib/ContentManager/Models/Activity.cs
  Source/Contrib/ContentManager/Models/Service.cs
  Source/Menu/MainForm.cs
Labels: bug

#559 https://blueprints.launchpad.net/or/+spec/distributed-power: Distributed power cab display and controls
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/images/cabs-distributed-power.png
  Source/Documentation/Manual/images/physics-dpu-window.png
  Source/Documentation/Manual/physics.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/DistributedPowerInterface.cs
Labels: enhancement

#565 Correct Steam locomoti starting tractive effort.
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#560 https://blueprints.launchpad.net/or/+spec/label-for-cab-controls , by Jindrich
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ETCS/DriverMachineInterface.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#573 Fix wrong variable used in battery button
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#575 Correct information in manual
  Source/Documentation/Manual/physics.rst
Labels: bug, documentation

#577 Bug fix for https://bugs.launchpad.net/or/+bug/1959081 Webserver HUD has misaligned tabs
  Source/RunActivity/Viewer3D/WebServices/Web/HUD/index.html
Labels: bug
