Repository openrails/openrails, pull requests merged in 2023-08, with the labels that each got.

#858 Fix wheel animation problems
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: bug

#856 Add Alternate Syntax for Confusing Tokens
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: for-unstable

#861 Curve friction#1
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Sound.cs
Labels: bug

#821 Adds suppression of safety valves
  Source/Documentation/Manual/physics.rst
Labels: documentation
