Repository openrails/openrails, pull requests merged in 2023-09, with the labels that each got.

#859 Steam adhesion bug#1
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#860 Changes in the Car Operations Menu for the lines with brake information
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/images/driving-car-operations.png
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/RunActivity/Viewer3D/Popups/CarOperationsWindow.cs
Labels: enhancement, for-unstable

#862 Fix engine leak problem
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: bug

#872 Fix Retainer State Disappearing from HUD on Restore
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: bug

#871 Signal aspects are multiplied when reopening Dispatcher Window
  Source/RunActivity/Viewer3D/Debugging/DebugViewerForm.cs
Labels: bug

#864 Fixes for Undesired Emergency Applications
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/BrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SingleTransferPipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/EOT.cs
Labels: bug, for-unstable

#863 Alternate preset 3D cabviewpoints
  Source/Documentation/Manual/cabs.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/Commands.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#841 https://blueprints.launchpad.net/or/+spec/animating-trainset-windows
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/driving.rst
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/sound.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/AnimatedPart.cs
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
  Source/RunActivity/Viewer3D/Sound.cs
Labels: enhancement

#870 Fix water restore
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#866 Fix Articulation For 0-Axle Train Cars
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: bug, for-unstable

#831 poor mans switch panel on tablet
  Source/Documentation/Manual/images/switch-panel.png
  Source/Documentation/Manual/software-platform.rst
  Source/ORTS.Common/GetStringAttribute.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Door.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/CircuitBreaker.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/TractionCutOffRelay.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrackMonitorWindow.cs
  Source/RunActivity/Viewer3D/Processes/WebServerProcess.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/UserInput.cs
  Source/RunActivity/Viewer3D/Viewer.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchOnPanel.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchOnPanelDefinition.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchOnPanelStatus.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchPanelEvent.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchPanelModule.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchesOnPanel.cs
  Source/RunActivity/Viewer3D/WebServices/Web/SwitchPanel/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/SwitchPanel/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/SwitchPanel/index2.css
  Source/RunActivity/Viewer3D/WebServices/Web/SwitchPanel/index2.html
  Source/RunActivity/Viewer3D/WebServices/Web/SwitchPanel/index2.js
  Source/RunActivity/Viewer3D/WebServices/Web/index.html
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
Labels: enhancement, for-unstable

#855 Adds new route from TrainSimulations
  Website/openrails.org/discover/news/index.php
  Website/openrails.org/index.php
Labels: website

#853 Notify out of focus
  Source/RunActivity/Viewer3D/Popups/OutOfFocusWindow.cs
  Source/RunActivity/Viewer3D/Popups/Window.cs
  Source/RunActivity/Viewer3D/Popups/WindowManager.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: for-unstable

#857 Adding Air Flow Meters
  Source/Documentation/Manual/appendices.rst
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/driving.rst
  Source/ORTS.Common/Conversions.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
Labels: for-unstable

#877 Initail build of duplex steam
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
Labels: enhancement
