Repository openrails/openrails, pull requests merged in 2023-05, with the labels that each got.

#828 Harmless part of "Improvements for braking systems"
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement

#826 Bug fix for Crash when switching cab https://bugs.launchpad.net/or/+bug/2018230
  Source/RunActivity/Viewer3D/Cameras.cs
Labels: bug

#822 battery switch two buttons option in combination with a delay
  Source/Documentation/Manual/physics.rst
Labels: documentation

#732 Improvements for air brakes
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SMEBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SingleTransferPipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/StraightVacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: enhancement

#751 Web interface to control cab controls with external hardware
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/UserInput.cs
  Source/RunActivity/Viewer3D/UserInputExternal.cs
  Source/RunActivity/Viewer3D/UserInputRailDriver.cs
  Source/RunActivity/Viewer3D/WebServices/ControlValue.cs
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
Labels: enhancement

#832 Fix Cruise Control together with Train Brake
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs
Labels: bug
