Repository openrails/openrails, pull requests merged in 2023-06, with the labels that each got.

#834 Replaces email service with FormSpark
  Website/openrails.org/contact/form.php
Labels: website

#836 Adds policy on crashes and derailments
  Website/openrails.org/contribute/team-policies/index.php
Labels: website

#837 copies website policies to repo
  Docs/Policies.md
Labels: documentation

#825 2D Cabview controls for side viewpoints https://blueprints.launchpad.net/or/+spec/2dcabview-controls-for-side-views
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
Labels: enhancement

#823 Select track sound volume percent retained in .eng and .wag files
  Source/Documentation/Manual/sound.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/RunActivity/Viewer3D/Sound.cs
Labels: enhancement

#818 Allow independent drive axles for locomotives
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/ElectricMotor.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/InductionMotor.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/SeriesMotor.cs
  Source/RunActivity/Viewer3D/InfoDisplay.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: refactoring

#803 Various adjustments to steam adhesion
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#813 Refactored garbage generators
  Source/ORTS.Common/Filter.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/SignalConfigurationFile.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/LevelCrossing.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/LocomotivePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/Signalling/SIGSCRfile.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalHead.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalObject.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/Orts.Simulation/Simulation/Signalling/TrackCircuitSection.cs
  Source/Orts.Simulation/Simulation/Signalling/TrackCircuitState.cs
  Source/Orts.Simulation/Simulation/Signalling/TrainQueue.cs
  Source/Orts.Simulation/Simulation/Traveller.cs
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/RenderFrame.cs
  Source/RunActivity/Viewer3D/RoadCars.cs
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: refactoring

#835 Correct Brake Shoe Force Calculation
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SingleTransferPipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/StraightVacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/FreightAnimations.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: bug

#843 Fix for https://bugs.launchpad.net/or/+bug/2024295 Freight weight only added for first wagon
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/FreightAnimations.cs
Labels: bug

#830 Electric locomotive hot start
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSElectricLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/BatterySwitch.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ElectricPowerSupply.cs
Labels: enhancement

#840 Bug fix for sanding max speed not working
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug, for-unstable
