Repository openrails/openrails, pull requests merged in 2023-12, with the labels that each got.

#878 Implement Polach Adhesion
  Source/Documentation/Manual/physics.rst
  Source/ORTS.Common/Conversions.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/ElectricMotor.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/InductionMotor.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/SeriesMotor.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement, for-unstable

#883 SwitchPanel disconnect/connect handling
  Source/RunActivity/Viewer3D/WebServices/Web/SwitchPanel/index2.css
  Source/RunActivity/Viewer3D/WebServices/Web/SwitchPanel/index2.html
  Source/RunActivity/Viewer3D/WebServices/Web/SwitchPanel/index2.js
Labels: enhancement

#874 Dynamic brake controller refactoring
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSBrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MultiPositionController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement

#888 docs: Document player application model
  Docs/Architecture.md
Labels: documentation

#875 Bug fix for https://bugs.launchpad.net/or/+bug/2036346 Player train switching doesn't work with 3D cabs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug

#898 Extra line with all the arguments for debugging purposes in logfile
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
Labels: enhancement

#904 fix: adds downgrade to low precision
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Popups/HelpWindow.cs
Labels: bug

#894 Correct Decrease Colour
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug

#893 Signal errors
  Source/Orts.Formats.Msts/SignalScripts.cs
  Source/Orts.Simulation/Simulation/Signalling/SIGSCRfile.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalObject.cs
Labels: bug
