Repository openrails/openrails, pull requests merged in 2023-04, with the labels that each got.

#767 Refine sunrise and sunset
  Source/Orts.Formats.Msts/EnvironmentFile.cs
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/RunActivity/Viewer3D/Common/SunMoonPos.cs
  Source/RunActivity/Viewer3D/MSTSSky.cs
  Source/RunActivity/Viewer3D/Sky.cs
Labels: bug, enhancement

#809 Some on-screen messages not suppressed, Bug #2008012
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/RunActivity/Viewer3D/Popups/NoticeWindow.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug, for-unstable

#814 Bug fix for https://bugs.launchpad.net/or/+bug/2013969 Crash after uncoupling player loco of a train with EOT
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
Labels: bug

#817 weblink updated
  Website/openrails.org/trade/index.php
Labels: website

#816 Bug fix for https://bugs.launchpad.net/or/+bug/2014992 EOT can't be dismounted after train reversal
  Source/Orts.Simulation/Common/Commands.cs
  Source/RunActivity/Viewer3D/Popups/EOTListWindow.cs
Labels: bug

#820 delay option for masterkey does not delay switch off
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/MasterKey.cs
Labels: bug
