Repository openrails/openrails, pull requests merged in 2023-01, with the labels that each got.

#744 Fixed and improved cabview control conditions related to power supply state
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/DistributedPowerInterface.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ETCS/DriverMachineInterface.cs
Labels: enhancement

#759 fix: Improve sky dome distortion causing bug #1471416
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/Common/SunMoonPos.cs
  Source/RunActivity/Viewer3D/Lights.cs
  Source/RunActivity/Viewer3D/MSTSSky.cs
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/ParticleEmitter.cs
  Source/RunActivity/Viewer3D/Precipitation.cs
  Source/RunActivity/Viewer3D/RenderFrame.cs
  Source/RunActivity/Viewer3D/Signals.cs
  Source/RunActivity/Viewer3D/Sky.cs
  Source/RunActivity/Viewer3D/SkyInterpolation.cs
Labels: bug

#762 News and trade updated
  Website/openrails.org/discover/news/index.php
  Website/openrails.org/index.php
  Website/openrails.org/trade/index.php
Labels: website

#749 OpenRailway Map
  Source/Orts.Simulation/Common/WorldLatLon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/WebServices/Web/Map/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/Map/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/Map/locomotive.png
  Source/RunActivity/Viewer3D/WebServices/Web/index.html
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
Labels: enhancement, for-unstable

#748 latitude/longitude fix for bug 1393111
  Source/Orts.Simulation/Common/WorldLatLon.cs
Labels: bug, for-unstable

#758 Steam wheel slip#1
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement

#754 Container weights: https://blueprints.launchpad.net/or/+spec/container-weights
  Source/Documentation/Manual/features-rollingstock.rst
  Source/ORTS.Common/enums.cs
  Source/Orts.Formats.Msts/ActivityFile.cs
  Source/Orts.Formats.OR/ContainerFile.cs
  Source/Orts.Formats.OR/LoadStationsPopulationFile.cs
  Source/Orts.Simulation/Simulation/Container.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/FreightAnimations.cs
Labels: enhancement

#763 build: Remove use of SolutionDir which is not supported everywhere
  Source/ContentChecker/ContentChecker.csproj
  Source/Contrib/ActivityEditor/ActivityEditor/ActivityEditor.csproj
  Source/Contrib/ActivityEditor/LibAE/LibAE.csproj
  Source/Contrib/DataCollector/DataCollector.csproj
  Source/Contrib/TrackViewer/TrackViewer.csproj
  Source/Menu/Menu.csproj
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/Orts.Formats.Msts/Orts.Formats.Msts.csproj
  Source/Orts.Formats.OR/Orts.Formats.OR.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.OR/Orts.Parsers.OR.csproj
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/RunActivity/RunActivity.csproj
  Source/Tests/Tests.csproj
Labels: infrastructure

#746 Website release 1.5.1
  Website/openrails.org/discover/license/index.php
  Website/openrails.org/discover/roadmap/index.php
  Website/openrails.org/discover/version-1-5/index.php
  Website/openrails.org/discover/version-1-5/title.php
  Website/openrails.org/discover/was-our-plans/index.php
  Website/openrails.org/discover/was-our-plans/title.php
  Website/openrails.org/download/program/index.php
  Website/openrails.org/download/source/index.php
  Website/openrails.org/index.php
  Website/openrails.org/learn/faq/install.php
  Website/openrails.org/shared/menu.php
  Website/openrails.org/shared/now_at_version_1_5.png
  Website/openrails.org/shared/now_at_version_1_6.png
  Website/openrails.org/shared/now_at_version_1_x.png
Labels: website

#761 fix: Allow 100% cloud-free skys by making 0% overcast = 0% clouds
  Source/RunActivity/Viewer3D/Shaders.cs
Labels: bug

#747 Update Hungarian translations
  Source/Locales/Contrib/hu.po
  Source/Locales/Updater/hu.po
Labels: locales

#717 Allow unlimited number of TCS cabview controls
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSElectricLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/EOT.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/DistributedPowerInterface.cs
Labels: enhancement

#765 Bug fix for https://bugs.launchpad.net/or/+bug/2002183 OK to proceed sound played wrongly
  Source/Orts.Simulation/Simulation/Activity.cs
Labels: bug

#764 fix: Improve sky dome distortion causing bug #1471416
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/Sky.cs
Labels: bug

#760 Updated EditorConfig with .NET and StyleCop analyzer configuration
  Source/.editorconfig
Labels: infrastructure

#719 Upgraded to MonoGame 3.8.0 (+ small update for other libraries)
  .config/dotnet-tools.json
  .gitattributes
  Source/3rdPartyLibs/MonoGame/CppNet.dll
  Source/3rdPartyLibs/MonoGame/MonoGame.Framework.Content.Pipeline.dll
  Source/3rdPartyLibs/MonoGame/MonoGame.Framework.Content.Pipeline.xml
  Source/3rdPartyLibs/MonoGame/MonoGame.Framework.dll
  Source/3rdPartyLibs/MonoGame/MonoGame.Framework.xml
  Source/3rdPartyLibs/MonoGame/SharpDX.D3DCompiler.dll
  Source/3rdPartyLibs/MonoGame/SharpDX.DXGI.dll
  Source/3rdPartyLibs/MonoGame/SharpDX.Direct3D11.dll
  Source/3rdPartyLibs/MonoGame/SharpDX.XAudio2.dll
  Source/3rdPartyLibs/MonoGame/SharpDX.dll
  Source/ContentChecker/ContentChecker.csproj
  Source/Contrib/ActivityEditor/ActivityEditor/ActivityEditor.csproj
  Source/Contrib/ActivityEditor/LibAE/LibAE.csproj
  Source/Contrib/ContentManager/ContentManager.csproj
  Source/Contrib/DataCollector/DataCollector.csproj
  Source/Contrib/DataConverter/DataConverter.csproj
  Source/Contrib/DataValidator/DataValidator.csproj
  Source/Contrib/SimulatorTester/SimulatorTester.csproj
  Source/Contrib/TrackViewer/TrackViewer.csproj
  Source/Launcher/Launcher.csproj
  Source/Menu/Menu.csproj
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Content/ORTS.Content.csproj
  Source/ORTS.IO/ORTS.IO.csproj
  Source/ORTS.Menu/ORTS.Menu.csproj
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Updater/ORTS.Updater.csproj
  Source/Orts.Formats.Msts/Orts.Formats.Msts.csproj
  Source/Orts.Formats.OR/Orts.Formats.OR.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.OR/Orts.Parsers.OR.csproj
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/RunActivity/PostBuildActions.bat
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Shaders.cs
  Source/Tests/Tests.csproj
  Source/Updater/Updater.csproj
Labels: enhancement

#735 Added new parameter for battery switch
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSControlTrailerCar.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSElectricLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/BatterySwitch.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/LocomotivePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/PassengerCarPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/SteamPowerSupply.cs
Labels: enhancement

#768 OpenRailway Map enhancements
  Source/Documentation/Manual/images/web-page-map.png
  Source/Documentation/Manual/software-platform.rst
  Source/ORTS.Common/InfoApiMap.cs
  Source/ORTS.Common/WorldLatLon.cs
  Source/Orts.Formats.Msts/TrackDatabaseFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/WebServices/Web/Map/arrow.png
  Source/RunActivity/Viewer3D/WebServices/Web/Map/diesel-locomotive-icon.png
  Source/RunActivity/Viewer3D/WebServices/Web/Map/electric-locomotive-icon.png
  Source/RunActivity/Viewer3D/WebServices/Web/Map/index.html
  Source/RunActivity/Viewer3D/WebServices/Web/Map/index.js
  Source/RunActivity/Viewer3D/WebServices/Web/Map/leaflet.rotatedMarker.js
  Source/RunActivity/Viewer3D/WebServices/Web/Map/locomotive.png
  Source/RunActivity/Viewer3D/WebServices/Web/Map/steam-locomotive-icon.png
  Source/RunActivity/Viewer3D/WebServices/WebServer.cs
Labels: for-unstable

#770 adds page for tutorial: Build Your Own Route
  Website/openrails.org/index.php
  Website/openrails.org/learn/build-route/index.php
  Website/openrails.org/learn/build-route/title.php
  Website/openrails.org/learn/manual-and-tutorials/index.php
  Website/openrails.org/shared/menu.php
Labels: website

#766 Control Car additional functionality
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSControlTrailerCar.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/GearBox.cs
Labels: enhancement

#773 Add watchdog ping to Train Processing
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
Labels: for-unstable
