Repository openrails/openrails, pull requests merged in 2023-07, with the labels that each got.

#808 Updated translations
  Source/Locales/Contrib/Contrib.pot
  Source/Locales/Contrib/ru.po
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/ru.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/ru.po
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/Orts.Formats.OR/Orts.Formats.OR.pot
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/ru.po
  Source/Locales/Updater/Updater.pot
Labels: locales

#847 Add additional default brakeshoe CoF
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: enhancement

#829 Improvements for air brakes #3 - Emergency valves
  Source/Documentation/Manual/physics.rst
  Source/Documentation/Manual/sound.rst
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: enhancement

#833 Implement brake relay valve
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/BrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SMEBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: enhancement

#849 Contributed projects and forking clarity
  Docs/Contributing.md
Labels: documentation

#850 Correct output of sound system info
  Source/ORTS.Common/SystemInfo.cs
Labels: bug

#852 Remove unneeded adhesion options
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#851 New Triple Valve Features
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: enhancement, for-unstable

#854 fix: Updating manual to match PR 647
  Source/Documentation/Manual/appendices.rst
  Source/Documentation/Manual/timetable.rst
Labels: documentation

#844 Animate axles separately
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement
