Repository openrails/openrails, pull requests merged in 2024-05, with the labels that each got.

#924 Default Asset Improvements
  Source/Documentation/Manual/news.rst
  Source/RunActivity/Content/Clouds01.png
  Source/RunActivity/Content/LightGlow.png
  Source/RunActivity/Content/SignalLightGlow.png
  Source/RunActivity/Content/SkyDome1.png
  Source/RunActivity/Content/Snowflake.png
  Source/RunActivity/Content/StarDome1.bmp
  Source/RunActivity/Content/Starmap_N.png
  Source/RunActivity/Content/Starmap_S.png
  Source/RunActivity/Content/WindowScrollbar.png
Labels: enhancement

#927 AI Train Power Supply/Lights Fix
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
Labels: bug

#942 Fix wrong case in filename
  Source/Menu/Properties/Resources.resx
Labels: refactoring

#941 AI Penalty Lights Fix
  Source/RunActivity/Viewer3D/Lights.cs
Labels: bug

#940 Browser HUD column alignment improvements
  Source/RunActivity/Viewer3D/WebServices/Web/HUD/index.js
Labels: for-unstable

#939 Add KM/HOUR/MIN to Cabview Units + Custom Units
  Source/Documentation/Manual/cabs.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: enhancement
