Repository openrails/openrails, pull requests merged in 2024-12, with the labels that each got.

#891 Auto save
  Source/Documentation/Manual/images/options-general.png
  Source/Documentation/Manual/options.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/RunActivity/Viewer3D/Popups/QuitWindow.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#1011 adds INI File to Appendix
  Source/Documentation/Manual/appendices.rst
Labels: documentation

#1014 Bug fix for https://bugs.launchpad.net/or/+bug/2091895 Train disappears from train list window
  Source/Orts.Simulation/Simulation/Simulator.cs
Labels: bug

#1008 Fix: TrainCarOperations doesn't work as expected after resume.
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsWindow.cs
Labels: bug

#1020 Bug fix for https://bugs.launchpad.net/or/+bug/2092489 Containers not appearing in timetable mode
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
Labels: bug

#1017 Refactor namespaces in Launcher
  Source/Launcher/Launcher.csproj
  Source/Launcher/Program.cs
Labels: refactoring

#1018 Refactor namespaces in Menu
  Source/Menu/ContentForm.Designer.cs
  Source/Menu/ContentForm.cs
  Source/Menu/ImportExportSaveForm.Designer.cs
  Source/Menu/ImportExportSaveForm.cs
  Source/Menu/KeyInputControl.Designer.cs
  Source/Menu/KeyInputControl.cs
  Source/Menu/KeyInputEditControl.Designer.cs
  Source/Menu/KeyInputEditControl.cs
  Source/Menu/MainForm.Designer.cs
  Source/Menu/MainForm.cs
  Source/Menu/Menu.csproj
  Source/Menu/Notifications/NotificationManager.cs
  Source/Menu/Notifications/NotificationPage.cs
  Source/Menu/Notifications/Notifications.cs
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/Menu/OptionsRailDriver.cs
  Source/Menu/Program.cs
  Source/Menu/Properties/Resources.Designer.cs
  Source/Menu/RDButtonInputControl.Designer.cs
  Source/Menu/RDButtonInputControl.cs
  Source/Menu/ResumeForm.Designer.cs
  Source/Menu/ResumeForm.cs
  Source/Menu/SortableBindingList.cs
  Source/Menu/Task.cs
  Source/Menu/TestingForm.Designer.cs
  Source/Menu/TestingForm.cs
Labels: refactoring
