Repository openrails/openrails, pull requests merged in 2024-08, with the labels that each got.

#975 Bug fix for https://bugs.launchpad.net/or/+bug/2076133 Crash when AI train dissolves near camera
  Source/RunActivity/Viewer3D/Lights.cs
Labels: bug

#976 Increased center of gravity range
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
Labels: for-unstable

#922 Autopilot for timetable mode
  Source/Documentation/Manual/driving.rst
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/CircuitBreaker.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
  Source/RunActivity/Viewer3D/Lights.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Popups/HelpWindow.cs
  Source/RunActivity/Viewer3D/Popups/NextStationWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainDPUWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainListWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Viewer.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchOnPanelStatus.cs
  Source/RunActivity/Viewer3D/WebServices/TrainDrivingDisplay.cs
Labels: enhancement

#903 Downloading route content (Github, zip)
  Source/Documentation/Manual/images/download-content-form.png
  Source/Documentation/Manual/images/start-activity.png
  Source/Documentation/Manual/start.rst
  Source/Menu/DownloadContentForm.Designer.cs
  Source/Menu/DownloadContentForm.cs
  Source/Menu/DownloadContentForm.resx
  Source/Menu/MainForm.Designer.cs
  Source/Menu/MainForm.cs
  Source/Menu/Menu.csproj
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Settings/ContentRouteSettings.cs
  Source/ORTS.Settings/ContentSettings.cs
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Settings/UserSettings.cs
Labels: enhancement, for-unstable
