Repository openrails/openrails, pull requests merged in 2024-02, with the labels that each got.

#908 feat: supports switching adhesion precisions
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
Labels: enhancement

#914 Adjustments to Duplex steam
  Source/Documentation/Manual/physics.rst
  Source/ORTS.Common/Conversions.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/SteamEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/WebServices/TrainDrivingDisplay.cs
Labels: enhancement, for-unstable

#915 Correct calculation error with curve friction
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: bug, for-unstable

#917 Lighting Configuration Enhancements
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/news.rst
  Source/Documentation/Manual/physics.rst
  Source/Orts.Formats.Msts/LightCollection.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/RunActivity/Viewer3D/Lights.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
  Source/RunActivity/Viewer3D/Trains.cs
Labels: enhancement, for-unstable
