Repository openrails/openrails, pull requests merged in 2024-11, with the labels that each got.

#994 2 fixes in the OR manual
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/operation.rst
Labels: documentation

#988 Conditional sound, blueprint https://blueprints.launchpad.net/or/+spec/conditional-sound
  Source/Documentation/Manual/sound.rst
  Source/Orts.Formats.Msts/SoundManagmentFile.cs
  Source/RunActivity/Viewer3D/Sound.cs
Labels: enhancement

#997 Disable independent brake syncing by default
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#999 adds to section New Since Previous Version
  Source/Documentation/Manual/news.rst
Labels: documentation

#972 On Map window color changed switch or signal is not changed
  Source/RunActivity/Viewer3D/Map/MapForm.cs
Labels: bug

#984 Player train switching for timetable mode
  Source/Documentation/Manual/driving.rst
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/Popups/TrainListWindow.cs
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
Labels: enhancement

#954 Multiple Track Profiles & Superelevation Rewrite
  Source/Documentation/How to Provide Track Profiles for Open Rails Dynamic Track.docm
  Source/Documentation/Manual/appendices.rst
  Source/Documentation/Manual/developing.rst
  Source/Documentation/Manual/features-route.rst
  Source/Documentation/Manual/images/options-experimental.png
  Source/Documentation/Manual/news.rst
  Source/Documentation/Manual/options.rst
  Source/Documentation/Manual/physics.rst
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/ORTS.Common/Conversions.cs
  Source/ORTS.Common/Coordinates.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Formats.Msts/RouteFile.cs
  Source/Orts.Formats.Msts/TrackDatabaseFile.cs
  Source/Orts.Formats.OR/AETraveller.cs
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Activity.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/SuperElevation.cs
  Source/Orts.Simulation/Simulation/Traveller.cs
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/DynamicTrack.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
  Source/RunActivity/Viewer3D/Scenery.cs
  Source/RunActivity/Viewer3D/Shapes.cs
  Source/RunActivity/Viewer3D/SuperElevation.cs
  Source/RunActivity/Viewer3D/Viewer.cs
  Source/RunActivity/Viewer3D/Wire.cs
  Source/RunActivity/Viewer3D/World.cs
Labels: enhancement, refactoring

#991 Fix TrainCarOperations no interacts AltPgDn AltPgUp.
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsViewerWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsWindow.cs
  Source/RunActivity/Viewer3D/Viewer.cs
  Source/RunActivity/Viewer3D/WebServices/TrainCarOperationsWebpage.cs
Labels: bug

#995 Fix: TrainCarOperations and TrainOperationsViewer windows overlap.
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsViewerWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsWindow.cs
Labels: bug

#1006 Bugfix: Content Form exception when there is manually installed content in a top level directory.
  Source/Menu/ContentForm.cs
Labels: bug, for-unstable

#953 Fix Lights Crash on Corrupt Shapes
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: bug

#1004 Bugfix/fix train car operations brakehoses not sync coupling cars
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Content/TrainOperations/TrainOperationsMap32.png
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsViewerWindow.cs
Labels: bug
