Repository openrails/openrails, pull requests merged in 2024-06, with the labels that each got.

#947 Fix .ace Textures Not Being Used as Fallback for Missing .dds
  Source/RunActivity/Viewer3D/Materials.cs
Labels: bug

#945 Display tractive force instead of compensated out force
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: bug

#943 Dynamic Brakes Behavior & Display Improvements
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: bug, refactoring

#948 Fix Cycling Lights
  Source/RunActivity/Viewer3D/Lights.cs
Labels: bug

#955 Copy dynamic brake speeds from other vehicles
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#950 Ctrl-F5 showing yellow rectangles where mouse left button is active
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/RunActivity/Viewer3D/Popups/ControlRectangle.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ETCS/DriverMachineInterface.cs
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: enhancement

#951 fix: Fix watchdog process state name
  Source/RunActivity/Viewer3D/Processes/WatchdogProcess.cs
Labels: bug
