Repository openrails/openrails, pull requests merged in 2024-07, with the labels that each got.

#912 New Triple Valve Features Vol. 2
  Source/Documentation/Manual/appendices.rst
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/physics.rst
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/BrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SingleTransferPipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/StraightVacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/FreightAnimations.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/AnimatedPart.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
Labels: enhancement, for-unstable

#949 Oil Burning Locomotive
  Source/Documentation/Manual/physics.rst
  Source/Documentation/Manual/sound.rst
  Source/Orts.Formats.Msts/ActivityFile.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/AIs/AI.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/Popups/HelpWindow.cs
Labels: enhancement

#967 Fix AI Lights After Reversing Points
  Source/RunActivity/Viewer3D/Lights.cs
Labels: bug

#964 fix: Warning CA1417: Do not use the 'OutAttribute' for string parameter
  Source/ORTS.Settings/InputSettings.cs
Labels: bug

#966 fix: Warning CS0618: 'string.Copy(string)' is obsolete
  Source/ORTS.Menu/ORTimetables.cs
  Source/Orts.Formats.Msts/SignalConfigurationFile.cs
  Source/Orts.Formats.Msts/SignalScripts.cs
  Source/Orts.Formats.Msts/TrackDatabaseFile.cs
  Source/Orts.Formats.OR/AESignals.cs
  Source/Orts.Formats.OR/TimetableFile.cs
  Source/Orts.Formats.OR/TimetableGroupFile.cs
  Source/Orts.Simulation/MultiPlayer/Message.cs
  Source/Orts.Simulation/Simulation/AIs/AIPath.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Activity.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Signalling/DeadlockInfo.cs
  Source/Orts.Simulation/Simulation/Signalling/PlatformDetails.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalWorldObject.cs
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
  Source/Orts.Simulation/Simulation/Timetables/TTPool.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTurntable.cs
  Source/RunActivity/Viewer3D/Popups/NextStationWindow.cs
  Source/RunActivity/Viewer3D/Popups/TTDetachWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrackMonitorWindow.cs
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
Labels: bug

#965 style: Renormalize line endings
  Source/Locales/Contrib/Contrib.pot
  Source/Locales/Menu/Menu.pot
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/Orts.Formats.OR/Orts.Formats.OR.pot
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/Updater/Updater.pot
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
Labels: refactoring

#969 Bugfix refocus to the main window when opening the map window
  Source/RunActivity/Viewer3D/Map/MapForm.cs
Labels: bug, for-unstable
