Repository openrails/openrails, pull requests merged in 2024-04, with the labels that each got.

#910 Allow building code using .NET 6 (Windows)
  Source/ContentChecker/ContentChecker.csproj
  Source/Contrib/ActivityEditor/ActivityEditor/ActivityEditor.csproj
  Source/Contrib/ActivityEditor/LibAE/LibAE.csproj
  Source/Contrib/ContentManager/ContentManager.csproj
  Source/Contrib/DataCollector/DataCollector.csproj
  Source/Contrib/DataConverter/DataConverter.csproj
  Source/Contrib/DataValidator/DataValidator.csproj
  Source/Contrib/SimulatorTester/SimulatorTester.csproj
  Source/Contrib/TrackViewer/TrackViewer.csproj
  Source/Launcher/Launcher.csproj
  Source/Menu/MainForm.cs
  Source/Menu/Menu.csproj
  Source/Menu/ResumeForm.cs
  Source/Menu/TestingForm.cs
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Content/ORTS.Content.csproj
  Source/ORTS.IO/ORTS.IO.csproj
  Source/ORTS.Menu/ORTS.Menu.csproj
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Updater/ORTS.Updater.csproj
  Source/Orts.Formats.Msts/Orts.Formats.Msts.csproj
  Source/Orts.Formats.OR/Orts.Formats.OR.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.OR/Orts.Parsers.OR.csproj
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Processes/WatchdogProcess.cs
  Source/Tests/Tests.csproj
  Source/Updater/Updater.csproj
Labels: infrastructure

#930 Further enhancements for duplex locoomotive
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug, enhancement

#933 Fix AI DM crashing
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug, for-unstable

#925 Fix brakeshoe force bug
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: bug

#935 Correct bug created in diesel electric locomotive
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#934 Fix bug 1944070: ContentManager search exception.
  Source/Contrib/ContentManager/ContentManagerGUI.cs
Labels: bug

#937 Adds missing API cab controls to Manual
  Source/Documentation/Manual/images/web-page-cab-controls.png
  Source/Documentation/Manual/software-platform.rst
Labels: documentation
