Repository openrails/openrails, pull requests merged in 2024-03, with the labels that each got.

#916 Distributed Power Air Brake Synchronization
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/physics.rst
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/RunActivity/Viewer3D/Popups/TrainDPUWindow.cs
Labels: enhancement, for-unstable

#920 Update RailDriver in Manual
  Source/Documentation/Manual/images/options-raildriver-assignment.png
  Source/Documentation/Manual/images/options-raildriver-calibration-message.png
  Source/Documentation/Manual/images/options-raildriver-calibration.png
  Source/Documentation/Manual/options.rst
Labels: documentation

#911 docs: Add refactoring as a special type of PR
  Docs/Contributing.md
Labels: documentation

#926 Lights Bugfixes
  Source/RunActivity/Viewer3D/Lights.cs
Labels: bug

#928 Fix Missing Initializations From Copy in MSTSLocomotive
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug
