Repository openrails/openrails, pull requests merged in 2024-09, with the labels that each got.

#971 fix: Restore assembly info which allows platform compatibility checks
  Source/ORTS.Settings/ORTS.Settings.csproj
Labels: bug

#973 fix: Using singular target framework to allow for different platforms across different projects
  Source/ContentChecker/ContentChecker.csproj
  Source/Contrib/ActivityEditor/ActivityEditor/ActivityEditor.csproj
  Source/Contrib/ActivityEditor/LibAE/LibAE.csproj
  Source/Contrib/ContentManager/ContentManager.csproj
  Source/Contrib/DataCollector/DataCollector.csproj
  Source/Contrib/DataConverter/DataConverter.csproj
  Source/Contrib/DataValidator/DataValidator.csproj
  Source/Contrib/SimulatorTester/SimulatorTester.csproj
  Source/Contrib/TrackViewer/TrackViewer.csproj
  Source/Launcher/Launcher.csproj
  Source/Menu/Menu.csproj
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Content/ORTS.Content.csproj
  Source/ORTS.IO/ORTS.IO.csproj
  Source/ORTS.Menu/ORTS.Menu.csproj
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Updater/ORTS.Updater.csproj
  Source/Orts.Formats.Msts/Orts.Formats.Msts.csproj
  Source/Orts.Formats.OR/Orts.Formats.OR.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.OR/Orts.Parsers.OR.csproj
  Source/Orts.Simulation/Orts.Simulation.csproj
  Source/RunActivity/RunActivity.csproj
  Source/Tests/Tests.csproj
  Source/Updater/Updater.csproj
Labels: bug

#978 fix: adds MilepostUnitsMiles to Manual
  Source/Documentation/Manual/options.rst
Labels: documentation

#979 fix: update to news items
  Source/Documentation/Manual/news.rst
Labels: documentation

#974 Bug fix for https://bugs.launchpad.net/or/+bug/2076034 Doors remain open in AI trains
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
Labels: bug

#959 Fix TrackViewer crash on big zoom value
  Source/Contrib/TrackViewer/Drawing/DrawTerrain.cs
Labels: bug, for-unstable

#985 Correct bug with steam locomotive chuffing sound
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
Labels: bug

#885 feat: Add notifications to Menu
  Source/Documentation/Manual/images/notification-error.png
  Source/Documentation/Manual/images/notification-icon.png
  Source/Documentation/Manual/images/notification-red-indicator.png
  Source/Documentation/Manual/images/notification-routes.png
  Source/Documentation/Manual/images/notification-settings.png
  Source/Documentation/Manual/images/notification-static.png
  Source/Documentation/Manual/images/notification-update-available.png
  Source/Documentation/Manual/images/notification-update-incompatible.png
  Source/Documentation/Manual/images/notification-update-installed.png
  Source/Documentation/Manual/start.rst
  Source/Documentation/Notifications.docx
  Source/Menu/MainForm.Designer.cs
  Source/Menu/MainForm.cs
  Source/Menu/MainForm.resx
  Source/Menu/Menu.csproj
  Source/Menu/Notifications/NotificationManager.cs
  Source/Menu/Notifications/NotificationPage.cs
  Source/Menu/Notifications/Notifications.cs
  Source/Menu/Program.cs
  Source/Menu/Properties/Resources.Designer.cs
  Source/Menu/Properties/Resources.resx
  Source/Menu/Resources/Notification-first.png
  Source/Menu/Resources/Notification-last.png
  Source/Menu/Resources/Notification-next.png
  Source/Menu/Resources/Notification-previous.png
  Source/Menu/Resources/chat_icon_new_message_transparent.png
  Source/Menu/Resources/chat_icon_no_message_transparent.png
  Source/ORTS.Common/SystemInfo.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/ORTS.Updater/UpdateManager.cs
Labels: enhancement

#799 Consolidated wind simulation
  Source/ORTS.Common/Conversions.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/Weather.cs
  Source/RunActivity/Content/PrecipitationShader.fx
  Source/RunActivity/Content/SkyShader.fx
  Source/RunActivity/Viewer3D/MSTSSky.cs
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/ParticleEmitter.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/Precipitation.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Shaders.cs
  Source/RunActivity/Viewer3D/Signals.cs
  Source/RunActivity/Viewer3D/Sky.cs
  Source/RunActivity/Viewer3D/SkyInterpolation.cs
  Source/RunActivity/Viewer3D/Weather.cs
  Source/RunActivity/Viewer3D/World.cs
Labels: enhancement
