Repository openrails/openrails, pull requests merged in 2024-01, with the labels that each got.

#906 Bug fix for https://bugs.launchpad.net/or/+bug/2047299 Crash loading a 3Dcab-only loco
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug

#909 Correct Control Car crash bug
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSControlTrailerCar.cs
Labels: bug, for-unstable

#913 chore: Add explict Read the Docs configuration file
  .readthedocs.yaml
  Source/Documentation/Manual/requirements.txt
Labels: infrastructure

#899 Duplex steam engines - Booster Engine addition
  Source/Documentation/Manual/physics.rst
  Source/Documentation/Manual/sound.rst
  Source/ORTS.Common/Input/UserCommand.cs
  Source/ORTS.Settings/InputSettings.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Formats.Msts/SoundManagmentFile.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Simulation/Confirmer.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/SteamEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/Axle.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSSteamLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/Sound.cs
Labels: enhancement, for-unstable
