Repository openrails/openrails, pull requests merged in 2024-10, with the labels that each got.

#970 feat: Remove unnecessary Windows.Forms usage
  Source/ContentChecker/ContentChecker.csproj
  Source/ContentChecker/Loader.cs
  Source/ContentChecker/Program.cs
  Source/Contrib/DataCollector/Program.cs
  Source/Contrib/DataConverter/Program.cs
  Source/Contrib/DataValidator/Program.cs
  Source/Contrib/SimulatorTester/Program.cs
  Source/Contrib/SimulatorTester/SimulatorTester.csproj
  Source/Menu/MainForm.cs
  Source/Menu/Options.cs
  Source/Menu/Program.cs
  Source/Menu/TestingForm.cs
  Source/ORTS.Common/ApplicationInfo.cs
  Source/ORTS.Common/ORTS.Common.csproj
  Source/ORTS.Common/SystemInfo.cs
  Source/ORTS.Common/VersionInfo.cs
  Source/ORTS.Settings/ORTS.Settings.csproj
  Source/ORTS.Settings/UpdateSettings.cs
  Source/ORTS.Settings/UserSettings.cs
  Source/ORTS.Updater/ORTS.Updater.csproj
  Source/ORTS.Updater/UpdateManager.cs
  Source/RunActivity/Program.cs
  Source/RunActivity/Viewer3D/Popups/HelpWindow.cs
  Source/RunActivity/Viewer3D/Processes/Game.cs
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
  Source/RunActivity/Viewer3D/Processes/WebServerProcess.cs
  Source/RunActivity/Viewer3D/Shaders.cs
  Source/Updater/UpdaterProgress.cs
Labels: enhancement

#987 fix: Temporary workaround for building with NET 5+
  Source/Menu/Notifications/NotificationManager.cs
Labels: bug

#993 Fix trainset windows documentation in OR manual
  Source/Documentation/Manual/features-rollingstock.rst
Labels: documentation

#952 Investigation - Pulsing graphics
  Source/Orts.Simulation/Simulation/Signalling/Signals.cs
Labels: bug

#990 Fix TrainDrivingInfo, some texts are misaligned.
  Source/Locales/ORTS.Menu/pt_PT.po
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/cs.po
  Source/Locales/RunActivity/da.po
  Source/Locales/RunActivity/de.po
  Source/Locales/RunActivity/fr.po
  Source/Locales/RunActivity/hu.po
  Source/Locales/RunActivity/pt-BR.po
  Source/Locales/RunActivity/ru.po
  Source/Locales/RunActivity/zh-CN.po
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
Labels: bug

#839 First phase of https://blueprints.launchpad.net/or/+spec/additional-cruise-control-parameters
  Source/Documentation/Manual/cruisecontrol.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs
Labels: enhancement

#989 Fix: TrainCarOperations-crashes-locales
  Source/Locales/RunActivity/cs.po
  Source/Locales/RunActivity/da.po
  Source/Locales/RunActivity/de.po
  Source/Locales/RunActivity/fr.po
  Source/Locales/RunActivity/hu.po
  Source/Locales/RunActivity/it.po
  Source/Locales/RunActivity/pt-BR.po
  Source/Locales/RunActivity/ru.po
  Source/Locales/RunActivity/zh-CN.po
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsViewerWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsWindow.cs
Labels: bug
