Repository openrails/openrails, pull requests merged in 2025-01, with the labels that each got.

#936 ContentManager Enhancement: show more info for consists
  Source/Contrib/ContentManager/ContentInfo.cs
  Source/Contrib/ContentManager/ContentManagerGUI.Designer.cs
  Source/Contrib/ContentManager/ContentManagerGUI.cs
  Source/Contrib/ContentManager/Models/Car.cs
  Source/Contrib/ContentManager/Models/Consist.cs
  Source/Orts.Formats.Msts/EngineFile.cs
  Source/Orts.Formats.Msts/WagonFile.cs
Labels: enhancement

#1027 docs: Update manual link to self-hosted version
  Source/Documentation/Manual/driving.rst
Labels: documentation

#1012 doc:adds 3 news items to Manual
  Source/Documentation/Manual/issues.rst
  Source/Documentation/Manual/news.rst
Labels: documentation

#1023 Fix: Adjusts division in F1 command window for longer descriptions
  Source/RunActivity/Viewer3D/Popups/HelpWindow.cs
Labels: bug

#981 Multiple type trainset lightglows
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Orts.Formats.Msts/LightCollection.cs
  Source/RunActivity/Content/LightGlow.png
  Source/RunActivity/Content/ORTSLightGlow.png
  Source/RunActivity/RunActivity.csproj
  Source/RunActivity/Viewer3D/Lights.cs
  Source/RunActivity/Viewer3D/Materials.cs
Labels: enhancement

#1025 Fix for Multiplayer: lost players cannot be kicked out https://bugs.launchpad.net/or/+bug/2092767
  Source/RunActivity/Viewer3D/Map/MapForm.cs
Labels: bug

#1022 Fix invalid brake controller detection
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
Labels: bug

#996 Replace dynamic brakes by engine brakes at low speeds
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: enhancement

#1028 Replace all compression code with System.IO.Compression
  Source/Launcher/Program.cs
  Source/Menu/ImportExportSaveForm.cs
  Source/Menu/Menu.csproj
  Source/Orts.Parsers.Msts/Orts.Parsers.Msts.csproj
  Source/Orts.Parsers.Msts/SBR.cs
  Source/Orts.Updater/Orts.Updater.csproj
  Source/Orts.Updater/UpdateManager.cs
Labels: refactoring

#1035 Fix: TrainDrivingInfo crashes if engineBrakeStatus is null.
  Source/RunActivity/Viewer3D/Popups/TrainDrivingWindow.cs
Labels: bug

#1009 Fix: TrainCarViewer overlaps when display size changed
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsViewerWindow.cs
Labels: bug
