Repository openrails/openrails, pull requests merged in 2025-05, with the labels that each got.

#1077 Fix SME brakes not working
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: bug

#1066 Log derailment, using TraceInformation.
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
Labels: for-unstable

#1079 Adds Polish transations
  Source/Locales/Contrib/Contrib.pot
  Source/Locales/Contrib/pl.po
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/pl.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/pl.po
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Menu/pl.po
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/ORTS.Settings/pl.po
  Source/Locales/Orts.Formats.OR/Orts.Formats.OR.pot
  Source/Locales/Orts.Formats.OR/pl.po
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/pl.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/pl.po
  Source/Locales/Updater/Updater.pot
  Source/Locales/Updater/pl.po
Labels: locales

#1070 Fix a NullReferenceException in TCS scripts
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
Labels: bug

#1078 Default PowerSupply script for steam locomotives
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ElectricTrainSupplySwitch.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/SteamPowerSupply.cs
Labels: bug, refactoring

#892 Signal Function OPP_SIG_ID_TRAINPATH
  Source/Orts.Formats.Msts/SignalScripts.cs
  Source/Orts.Simulation/Simulation/Signalling/SIGSCRfile.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalHead.cs
  Source/Orts.Simulation/Simulation/Signalling/SignalObject.cs
Labels: enhancement

#1067 Traction and dynamic brake retardation
  Source/Documentation/Manual/physics.rst
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSControlTrailerCar.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/MSTSNotchController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/CruiseControl.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/ElectricMotor.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerTransmissions/InductionMotor.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement, for-unstable

#1074 Gradient - commit 2024-16-12
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Timetables/ProcessTimetable.cs
  Source/Orts.Simulation/Simulation/Timetables/TTTrain.cs
Labels: enhancement

#1089 Fix Superelevation on Rigid Frame Rolling Stock Again
  Source/Menu/Options.cs
  Source/Orts.Settings/UserSettings.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
Labels: bug

#1090 Add null check to avoid crash on corrupt signal files
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
Labels: bug

#1094 Blended Braking Compatibility and Effectiveness Improvements
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: bug, enhancement
