Repository openrails/openrails, pull requests merged in 2025-03, with the labels that each got.

#1056 Check for null BrakemanBrakeController
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
Labels: bug

#1033 Multiple signal light textures per signal
  Source/Documentation/Manual/appendices.rst
  Source/Orts.Formats.Msts/SignalConfigurationFile.cs
  Source/RunActivity/Viewer3D/Signals.cs
Labels: enhancement

#1026 Fix for Multiplayer: remote trains chuff can't be heard https://bugs.launchpad.net/or/+bug/2092771
  Source/Orts.Simulation/Simulation/Physics/Train.cs
Labels: bug

#1058 Refactor notification parameters
  Source/Menu/Notifications/NotificationManager.cs
  Source/Menu/Notifications/Notifications.cs
Labels: refactoring

#1060 Deutsche Übersetzung leicht angepasst
  Source/Locales/Menu/de.po
  Source/Locales/RunActivity/de.po
Labels: locales

#1061 Fix F9 Web-page conflict.
  Source/RunActivity/Viewer3D/Cameras.cs
  Source/RunActivity/Viewer3D/WebServices/TrainCarOperationsWebpage.cs
Labels: bug

#961 Improvements for Power Supplies
  Source/Documentation/Manual/cabs.rst
  Source/Documentation/Manual/features-rollingstock.rst
  Source/Documentation/Manual/physics.rst
  Source/Orts.Common/Conversions.cs
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Parsers.Msts/STFReader.cs
  Source/Orts.Simulation/Common/Commands.cs
  Source/Orts.Simulation/Common/Events.cs
  Source/Orts.Simulation/Common/Scripting/BrakeController.cs
  Source/Orts.Simulation/Common/Scripting/Commands.cs
  Source/Orts.Simulation/Common/Scripting/Common.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/CircuitBreaker.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/Controllers/PantographSelector.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/Controllers/PowerLimitationSelector.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/Controllers/VoltageSelector.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/DieselPowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/DualModePowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/ElectricPowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/LocomotivePowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/PassengerCarPowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/PowerSupply.cs
  Source/Orts.Simulation/Common/Scripting/PowerSupply/TractionCutOffSubsytem.cs
  Source/Orts.Simulation/Common/Scripting/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSControlTrailerCar.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSDieselLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSElectricLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSSteamLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Controllers/BrakeController.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Battery.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/CircuitBreaker.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Controllers/BatterySwitch.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Controllers/MasterKey.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Controllers/PantographSelector.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Controllers/PowerLimitationSelector.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Controllers/VoltageSelector.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DieselPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/DualModePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ElectricPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/ILocomotivePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/IPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/LocomotivePowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Pantograph.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/PassengerCarPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/SteamEngine.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/SteamPowerSupply.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/TractionCutOffRelay.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/TrainControlSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/Orts.Simulation/Simulation/Simulator.cs
  Source/RunActivity/Viewer3D/Popups/HUDWindow.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSDieselLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSElectricLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
Labels: enhancement

#1063 Better Missing Track Section Error Message
  Source/Orts.Simulation/Simulation/Traveller.cs
  Source/RunActivity/Viewer3D/Processes/GameStateRunActivity.cs
Labels: enhancement

#1015 Enhancements for EP brakes
  Source/Documentation/Manual/physics.rst
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/MSTSBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/ManualBraking.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SMEBrakeSystem.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/SingleTransferPipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/StraightVacuumSinglePipe.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/VacuumSinglePipe.cs
  Source/RunActivity/Viewer3D/Popups/CarOperationsWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsViewerWindow.cs
  Source/RunActivity/Viewer3D/Popups/TrainCarOperationsWindow.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchOnPanelDefinition.cs
  Source/RunActivity/Viewer3D/WebServices/SwitchPanel/SwitchOnPanelStatus.cs
  Source/RunActivity/Viewer3D/WebServices/TrainCarOperationsWebpage.cs
Labels: enhancement
