Repository openrails/openrails, pull requests merged in 2025-04, with the labels that each got.

#1068 Build for online-only documentation files
  Build.cmd
Labels: infrastructure

#1065 Fix for PantographToggle sound event
  Source/Documentation/Manual/sound.rst
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSWagon.cs
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/PowerSupplies/Pantograph.cs
Labels: bug

#1045 Bugfix: Empty Start Time for Explore, and other issues loading from Menu Selection and Content Routes
  Source/Menu/MainForm.cs
Labels: bug, for-unstable

#1029 Superelevation Follow Up Fixes
  Source/Orts.Formats.Msts/TrackSectionsFile.cs
  Source/Orts.Simulation/Simulation/AIs/AITrain.cs
  Source/Orts.Simulation/Simulation/Physics/Train.cs
  Source/Orts.Simulation/Simulation/RollingStocks/TrainCar.cs
  Source/RunActivity/Viewer3D/DynamicTrack.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSWagonViewer.cs
  Source/RunActivity/Viewer3D/SuperElevation.cs
Labels: bug

#900 DMI in 3D cab + two more dials
  Source/Documentation/Manual/cabs.rst
  Source/RunActivity/Viewer3D/Materials.cs
  Source/RunActivity/Viewer3D/RollingStock/MSTSLocomotiveViewer.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ETCS/DriverMachineInterface.cs
  Source/RunActivity/Viewer3D/RollingStock/SubSystems/ETCS/SpeedDistanceMonitoring.cs
  Source/RunActivity/Viewer3D/Shapes.cs
Labels: enhancement, for-unstable

#1007 Russian localization up to 2025 Jan 3-rd
  Source/Locales/Contrib/Contrib.pot
  Source/Locales/Contrib/ru.po
  Source/Locales/Menu/Menu.pot
  Source/Locales/Menu/ru.po
  Source/Locales/ORTS.Common/ORTS.Common.pot
  Source/Locales/ORTS.Common/ru.po
  Source/Locales/ORTS.Menu/ORTS.Menu.pot
  Source/Locales/ORTS.Settings/ORTS.Settings.pot
  Source/Locales/Orts.Formats.OR/Orts.Formats.OR.pot
  Source/Locales/Orts.Simulation/Orts.Simulation.pot
  Source/Locales/Orts.Simulation/ru.po
  Source/Locales/RunActivity/RunActivity.pot
  Source/Locales/RunActivity/ru.po
  Source/Locales/Updater/Updater.pot
Labels: for-unstable, locales

#1030 Refactor settings, in prep for settings exporter
  Source/Orts.Common/SettingsBase.cs
  Source/Orts.Common/SettingsStore.cs
  Source/Orts.Settings/ContentSettings.cs
  Source/Orts.Settings/FolderSettings.cs
  Source/Orts.Settings/InputSettings.cs
  Source/Orts.Settings/RailDriverSettings.cs
  Source/Orts.Settings/TelemetrySettings.cs
  Source/Orts.Settings/UpdateSettings.cs
  Source/Orts.Settings/UpdateState.cs
  Source/Orts.Settings/UserSettings.cs
  Source/Orts.Updater/UpdateManager.cs
Labels: refactoring, for-unstable

#1052 Content Manager: Add axle count, and lowest derail force
  Source/Contrib/ContentManager/ContentInfo.cs
  Source/Contrib/ContentManager/ContentMSTS.cs
  Source/Contrib/ContentManager/Models/Car.cs
  Source/Contrib/ContentManager/Models/Consist.cs
  Source/Orts.Formats.Msts/EngineFile.cs
  Source/Orts.Formats.Msts/WagonFile.cs
Labels: for-unstable

#1080 arranges Options > System tab for longer texts
  Source/Menu/Options.Designer.cs
  Source/Menu/Options.cs
  Source/Menu/Options.resx
Labels: locales

#1071 Change cover image for v1.6
  Source/Documentation/Manual/images/cover_image.png
Labels: documentation
