Repository openrails/openrails, pull requests merged in 2025-07, with the labels that each got.

#1119 Re-add missing PR #1103
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: infrastructure

#1116 Fix Potential Hang in AnimatedPart.SetFrameWrap
  Source/RunActivity/Viewer3D/AnimatedPart.cs
Labels: bug

#1117 ORTS_PLAYER_DIESEL_ENGINE_STATE manual fix
  Source/Documentation/Manual/cabs.rst
Labels: bug, documentation

#1125 Lift #1096 into 1.6 release
  Source/RunActivity/Viewer3D/Viewer.cs
Labels: bug

#1138 Calculate wheel speed in simple adhesion
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#1140 Fix Cabview Animation Edge Case
  Source/Orts.Formats.Msts/CabViewFile.cs
  Source/Orts.Simulation/Simulation/RollingStocks/MSTSLocomotive.cs
Labels: bug

#1133 Minor Fix for Brake Pipe Charging
  Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
Labels: bug

#1144 update Spanish translations
  Source/Locales/Contrib/es.po
  Source/Locales/Menu/es.po
  Source/Locales/ORTS.Common/es.po
  Source/Locales/ORTS.Menu/es.po
  Source/Locales/ORTS.Settings/es.po
  Source/Locales/Orts.Formats.OR/es.po
  Source/Locales/Orts.Simulation/es.po
  Source/Locales/RunActivity/es.po
  Source/Locales/Updater/es.po
Labels: locales

#1146 Fix for pantograph events not sent in AI trains
  Source/Orts.Simulation/Common/Scripting/PowerSupply/LocomotivePowerSupply.cs
Labels: bug

#1148 Lift #1135 into 1.6 release
  Source/Menu/MainForm.cs
Labels: bug
